<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Time based activities Button</name>
   <tag></tag>
   <elementGuidId>efe0dc8c-59a4-4224-998f-1c16889d17f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timeItems123 > a.pull-right > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='timeItems123']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6424cecc-6648-4d06-9b6a-f206e5b48cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/v10/time-based-act.png</value>
      <webElementGuid>7c3dc72f-dd96-4d95-a726-f2b91fa0ae5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeItems123&quot;)/a[@class=&quot;pull-right&quot;]/img[1]</value>
      <webElementGuid>725c50fc-ef6f-4ca8-8e87-7d73f9cabcdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='timeItems123']/a/img</value>
      <webElementGuid>c65723ba-eb37-4932-82ac-b13eae0fd825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/img</value>
      <webElementGuid>cc9e1cd1-89b3-462e-8722-0ac6db497ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/v10/time-based-act.png']</value>
      <webElementGuid>b8c798b5-b659-4b7d-9ea9-bc3dfa63bf89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
