<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Time based activities</name>
   <tag></tag>
   <elementGuidId>78a848cc-e734-4276-ad90-9159d4d36738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#allTimeItems > h3 > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allTimeItems']/h3/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>196c2ac4-e37f-4926-9704-8daa20cb229b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time based activities</value>
      <webElementGuid>be23427f-5808-4eff-9a87-36d799ff12ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allTimeItems&quot;)/h3[1]/strong[1]</value>
      <webElementGuid>0b1d4b6b-ff4e-4337-a443-f9898fa6a599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allTimeItems']/h3/strong</value>
      <webElementGuid>ef4f037b-a119-493d-b5d7-57abd89137d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[2]/following::strong[1]</value>
      <webElementGuid>eb256412-f0fa-4bc4-8f59-3f89c9826a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[1]/preceding::strong[1]</value>
      <webElementGuid>2c5a4bef-c3b8-4489-b223-6d2c660f1494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Time based activities']/parent::*</value>
      <webElementGuid>a6e92f6f-1fd3-414e-bb15-db8792631585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/h3/strong</value>
      <webElementGuid>28bdce5b-29db-4aa4-b1a4-a2aa9d03ae5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Time based activities' or . = 'Time based activities')]</value>
      <webElementGuid>42f3dad0-6051-4173-b073-00805662d333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
