<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_010_Attendance</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>edab19de-274c-4a0e-a3b5-69437e172530</testSuiteGuid>
   <testCaseLink>
      <guid>3375a2ce-ea57-4156-92cb-ebfa39890562</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05 - Self Services/03 - Attendance/01 - Positive/TC_048_RegularizeAttendance</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>905988c4-9283-4ee1-ae4d-6fbe60166340</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ebfa944-d0d7-4e9c-8e76-8e1755c5ea96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>835ece84-a4f6-4c8c-b530-c830fd5e01eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>741f24b5-1d16-4196-8f2c-239a5d127a0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2194367-fa37-489f-ab00-6df2a5bb97c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5563f96e-c599-4526-9a94-5ca82f4859f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05 - Self Services/03 - Attendance/01 - Positive/TC_049_ViewDashboard</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5fbb4b62-24f6-4b90-9f7b-c0484d6cf471</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05 - Self Services/03 - Attendance/01 - Positive/TC_050_ViewDashboardFullPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>905988c4-9283-4ee1-ae4d-6fbe60166340</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ebfa944-d0d7-4e9c-8e76-8e1755c5ea96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>835ece84-a4f6-4c8c-b530-c830fd5e01eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>741f24b5-1d16-4196-8f2c-239a5d127a0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2194367-fa37-489f-ab00-6df2a5bb97c7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
