<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Login feature test</description>
   <name>TS_001_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>246a4302-91be-424b-a3a2-952584a42505</testSuiteGuid>
   <testCaseLink>
      <guid>aeff62e7-dc05-4017-af3d-3f3a6fd51c5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01 - Login/01_Positive/TC_001_LoginSuccess</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62487ccf-91c3-4206-a0d2-ac4797bf1266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50bb020-8ca9-4c67-bf12-27c4d48e5b12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ba68592-28f0-4c4d-a9a6-dcdaf9c8f482</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59681410-ffda-49bd-8158-bfa2e94d21a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01 - Login/02_Negative/TC_002_LoginInvalidUsername</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62487ccf-91c3-4206-a0d2-ac4797bf1266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50bb020-8ca9-4c67-bf12-27c4d48e5b12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ba68592-28f0-4c4d-a9a6-dcdaf9c8f482</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a43c8af-287d-41e7-86af-96ae1ac3cfaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01 - Login/02_Negative/TC_003_LoginInvalidPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62487ccf-91c3-4206-a0d2-ac4797bf1266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50bb020-8ca9-4c67-bf12-27c4d48e5b12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ba68592-28f0-4c4d-a9a6-dcdaf9c8f482</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
