<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Casual Leave three dots</name>
   <tag></tag>
   <elementGuidId>3b665330-476c-4c6e-aef7-54f2bb96572a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-ellipsis-h</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/div/a/span/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;_navBarId_renderTableHeaderArray_1706717310959_0&quot;)/span[1]/i[@class=&quot;fas fa-ellipsis-h&quot;][count(. | //*[@ref_element = 'Object Repository/TC04 - Dashboard/03 - Leave/TC_026_ApplyCasualLeave/Page_Home page/iframe_Self services_homePageFrame (1)']) = count(//*[@ref_element = 'Object Repository/TC04 - Dashboard/03 - Leave/TC_026_ApplyCasualLeave/Page_Home page/iframe_Self services_homePageFrame (1)'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7649e7b6-e5ea-4f80-ac88-be4dbf0e57cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-ellipsis-h</value>
      <webElementGuid>dd7ae99e-6430-44be-bb77-ab6900baba05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_navBarId_renderTableHeaderArray_1706717310959_0&quot;)/span[1]/i[@class=&quot;fas fa-ellipsis-h&quot;]</value>
      <webElementGuid>b7f05268-7f73-4dfe-8d39-956a6abeea7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/03 - Leave/TC_026_ApplyCasualLeave/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>432623a2-7757-49fa-bf28-52a7a78e8cb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='_navBarId_renderTableHeaderArray_1706717310959_0']/span/i</value>
      <webElementGuid>c67c1580-5715-4665-90e8-013ab26d016f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/a/span/i</value>
      <webElementGuid>7671ff4a-9840-491a-8ca9-cde47197c3e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
