<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Self services_homePageFrame (1)</name>
   <tag></tag>
   <elementGuidId>eec074da-abfa-4087-b0f7-e629e07d64e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e509ab58-29e0-4f79-9ecf-178f1e36e254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=c7rx7N8xkXknprpz06dlP2J%2FdJEzP4ngFbARIA2bIHenwFJJ7suSW+ATSBCWtA0VeFp8us9jRHmZeyi78fc7sw%3D%3D</value>
      <webElementGuid>94880f88-8331-48db-88e0-dc5eb3a1aa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>100c6090-3bc1-4851-861a-42094c8fae88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>3c35c8ff-9e91-4123-9cdb-ef34c33f5d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>e0b4eb56-33cf-4af7-b4fa-02aeb6198415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>bf358c50-08ba-41eb-9db9-ea6e3a867e35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>c4bd6e7b-0e26-4ae4-8c98-983e046be4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>1e4d1cbb-8990-4c3d-807f-67974b2b8c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>31dff658-6086-4b08-a738-0b935844eae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=c7rx7N8xkXknprpz06dlP2J%2FdJEzP4ngFbARIA2bIHenwFJJ7suSW+ATSBCWtA0VeFp8us9jRHmZeyi78fc7sw%3D%3D' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>9115012d-3f91-4510-92b5-2611fa42c227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
