<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Half Day Start Date</name>
   <tag></tag>
   <elementGuidId>98c4f1b4-4cd9-426f-adf4-5cf20b8d41bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstHalf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstHalf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41c07461-51a9-4834-9416-bf6afe750e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.firstHalf</value>
      <webElementGuid>07942960-a6f9-422e-b31e-220606464da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d5f7a280-78cf-4bda-8985-7de2488321c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstHalf</value>
      <webElementGuid>880327da-a1b7-4add-93cc-0c6190a02aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ece9653a-ccbe-4731-9ca1-09ea7eb6c31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:calculateDaysOnCheckBox('');return true;</value>
      <webElementGuid>ac661753-196d-4b34-86be-d99f99996214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHalf&quot;)</value>
      <webElementGuid>77c75914-db48-4760-ba01-c08308cd7c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/03 - Leave/TC_026_ApplyCasualLeave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>c394fa76-5a8d-4eca-b8b2-2d7d28560a57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstHalf']</value>
      <webElementGuid>8b03ddc6-6545-4b06-8031-a010d56505fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveDetailSection']/div/label/input</value>
      <webElementGuid>460d7a1e-6300-4900-a99c-296ede859882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/input</value>
      <webElementGuid>bb0396f2-2b25-4a7a-9f4f-43469225e1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataObject.firstHalf' and @id = 'firstHalf' and @type = 'checkbox']</value>
      <webElementGuid>513d5914-11aa-479f-82ac-e3c9bb7ab733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
