<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Reason</name>
   <tag></tag>
   <elementGuidId>ba15f1af-1f31-4006-8e74-2f230f7bde60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reasonForLeave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reasonForLeave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4d82adeb-bf84-4017-ba6f-d0b5f675ed3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a966743d-f448-4a2e-9d94-d09bcd5b5909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.reasonForLeave</value>
      <webElementGuid>a517992c-a351-4c05-89d6-1763c95423d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>textLimit(this, 1000);</value>
      <webElementGuid>d186d768-855f-413f-90fd-2a4af465e18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reasonForLeave</value>
      <webElementGuid>84352aeb-5162-454c-a87f-77c57fb32553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reason for leave</value>
      <webElementGuid>c79085bf-5657-4683-aa6f-2b6bf37b3f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>111d67a2-e707-44a3-a2e8-42c1209103af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reasonForLeave&quot;)</value>
      <webElementGuid>dc458879-0438-4a66-9ae5-236bcb2429d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/03 - Leave/TC_026_ApplyCasualLeave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>bafe67b4-d8e8-4ea7-ba98-24faf24c06e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reasonForLeave']</value>
      <webElementGuid>e542c50c-6d1e-4f21-9ec1-db4376a58181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[5]/div/div[3]/textarea</value>
      <webElementGuid>d9684213-5bc2-4e43-a654-4d5de8e1f51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0cc3ee08-0add-449b-98a2-89524fbfcf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'dataObject.reasonForLeave' and @id = 'reasonForLeave' and @placeholder = 'Reason for leave']</value>
      <webElementGuid>c8a556eb-5775-4f9b-bebd-a7491b25cabb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
