<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Font</name>
   <tag></tag>
   <elementGuidId>879f45eb-e497-4be9-ad7e-c1660863a1bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cke_combo_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='CKEDITOR.tools.callFunction(27,this);return false;']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c4ee98f-79c8-41a7-a77c-bee5184fa939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_combo_button</value>
      <webElementGuid>e82a248a-89e4-4e0b-8dab-9f3b5e88a397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Font Name</value>
      <webElementGuid>dc2bbd1b-7ea0-4c84-bf36-3e7ee91995c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a4ccc6da-1bc1-44ce-926e-4dba5b0a307c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void('Font Name')</value>
      <webElementGuid>6b495bd1-1b6f-41f3-a2a9-6c22744621f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ae291e7-de5d-4d4f-a75e-9e3aebcf4eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60454864-37b5-48af-9373-a8efa426ca7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_14_label</value>
      <webElementGuid>f2ee0d78-9e56-4550-8e6d-33057427aaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>d94b39c0-99d3-4f20-9ec6-4a2a1e8edee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(28,event,this);</value>
      <webElementGuid>c3c2b92d-e5cd-430d-b301-014cb3c46ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(29,event);</value>
      <webElementGuid>34e2e1c8-ad65-4ceb-8dab-2fe67b7c9e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CKEDITOR.tools.callFunction(27,this);return false;</value>
      <webElementGuid>4f49cbf4-786e-4845-8292-c036ad53b716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>852eb810-ccd8-4218-a00e-006c2bbddd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Font</value>
      <webElementGuid>a6817310-b38a-4931-94ee-73e0d22e23a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_14&quot;)/a[@class=&quot;cke_combo_button&quot;]</value>
      <webElementGuid>75a735fa-afb7-4fd9-9582-6f120adfb518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>2a5adc69-9f77-4f66-b009-2797bbf0af8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='CKEDITOR.tools.callFunction(27,this);return false;']</value>
      <webElementGuid>eeabbf3a-63da-4391-9ae1-e3acd99466e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_14']/a</value>
      <webElementGuid>33ad6ec4-893e-4ee1-bae8-6a06c0c0ede5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font'])[1]/following::a[1]</value>
      <webElementGuid>5f4d8009-5e4e-4b90-b68d-e4dd057071dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strikethrough'])[1]/following::a[1]</value>
      <webElementGuid>7b1f5021-869e-4dc9-90c3-9bc4928d14dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/preceding::a[1]</value>
      <webElementGuid>3da40848-d5d7-40b3-a3f2-ce254de4e3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:void('Font Name')&quot;)]</value>
      <webElementGuid>9ad35563-f37a-4efe-842b-fa42b4588a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/a</value>
      <webElementGuid>024f8fb6-3c05-47f8-b732-50c3918e83e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Font Name' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Font Name&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Font' or . = 'Font')]</value>
      <webElementGuid>2eebb643-4f48-4797-b31f-40a93f532c55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
