<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ItalicKeyboard shortcut CtrlI</name>
   <tag></tag>
   <elementGuidId>3a772cdd-f768-488f-8adf-c49dcace4caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cke_22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cke_22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac7e8a95-f397-4f31-9296-5c94175c098c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_22</value>
      <webElementGuid>5f36b968-62bb-4a4e-95ef-2a55ffa44544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_button cke_button__italic cke_button_off</value>
      <webElementGuid>25372121-d5d8-4eed-8440-81d133900d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void('Italic')</value>
      <webElementGuid>f3fb8e99-4b6a-4c94-b32b-bf44bc1cb244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Italic (Ctrl+I)</value>
      <webElementGuid>be873aa0-ae86-46cd-9fe0-9637fd826a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>31fbaa1a-2574-4e2d-8621-300145edc3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f8d38e4-5246-48d2-9824-c570194d114e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6710055e-54de-4d01-80d3-1e0ec9443977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_22_label</value>
      <webElementGuid>4598403a-65c1-41c5-9cb6-241bb0099d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cke_22_description</value>
      <webElementGuid>928198ab-bd8f-4ff7-ae78-443204893400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d8770630-bf84-47c5-b73b-69228d5eef9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c20fb358-9bc1-4d85-a935-e37352e4d48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(18,event);</value>
      <webElementGuid>c6807234-5d8f-4728-acf4-ee14e7cd1744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(19,event);</value>
      <webElementGuid>e64e6041-44e3-4390-8cfc-e67e2aa78694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CKEDITOR.tools.callFunction(20,this);return false;</value>
      <webElementGuid>74669812-8c17-414c-81d4-a798a41f4917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Italic Keyboard shortcut Ctrl+I</value>
      <webElementGuid>22abeead-1f1e-45bd-b4a5-014a5d46b747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_22&quot;)</value>
      <webElementGuid>0e5201fe-0228-4c91-b4cf-3006910777fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>a4c7ca3d-7aca-4b8d-8340-b9b5b24d111b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cke_22']</value>
      <webElementGuid>c6cbef47-d8d7-48cd-a164-1bd138a39bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_16']/span[3]/a[6]</value>
      <webElementGuid>89bbc1df-e70d-423d-9b8a-375f15cee991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold'])[1]/following::a[1]</value>
      <webElementGuid>076686aa-e7ee-470a-91e6-4808499299aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:void('Italic')&quot;)]</value>
      <webElementGuid>95b9092a-00df-4c4f-8b24-6f07259ccded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>43b3eb43-4534-430b-ada8-3c772f3c5e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cke_22' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Italic&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Italic (Ctrl+I)' and (text() = ' Italic Keyboard shortcut Ctrl+I' or . = ' Italic Keyboard shortcut Ctrl+I')]</value>
      <webElementGuid>9a8c1b87-a2cb-4814-bdae-b12fe8cbd6de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
