<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Size</name>
   <tag></tag>
   <elementGuidId>62455278-fd4c-4fad-9d30-6b6b65d69822</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cke_15 > a.cke_combo_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='CKEDITOR.tools.callFunction(30,this);return false;']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>899e9a26-ab03-4d1f-83cf-db352696fd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_combo_button</value>
      <webElementGuid>6f3472db-4c50-4ae6-985c-4ccdb276dd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Font Size</value>
      <webElementGuid>27de49b9-ee2c-4937-9eee-06cfa052a989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d9161ede-1300-481b-a55e-09aa6c485c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void('Font Size')</value>
      <webElementGuid>20bb6315-66d2-4f6c-b7d4-d7908c970292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76c6cab0-9d8f-4142-a5ef-9284ad271cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5247e37f-cc13-4515-bbe8-d6d4f2c2454e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_15_label</value>
      <webElementGuid>7e5c72bc-2020-4ad5-9b8a-8fa586cd7a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>a657bc0b-28ed-4a14-98c0-ab99bf402d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(31,event,this);</value>
      <webElementGuid>6201874d-68ad-42ce-8295-54d95e5c5e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(32,event);</value>
      <webElementGuid>45e20290-e393-4772-8f5a-0e63ffa39cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CKEDITOR.tools.callFunction(30,this);return false;</value>
      <webElementGuid>2019afba-c2cd-4996-b857-14683c5758c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>08cf3b1d-b78b-4280-9e3e-23e51b1b0d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Size</value>
      <webElementGuid>f4b776e5-0453-44aa-b2ce-b572d335f1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_15&quot;)/a[@class=&quot;cke_combo_button&quot;]</value>
      <webElementGuid>576ec13b-7793-4f62-a3c7-d5279e1531e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>152701ea-3c30-4c72-b1fc-76a389d45e09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='CKEDITOR.tools.callFunction(30,this);return false;']</value>
      <webElementGuid>7dd3384e-0054-454d-a0d2-0b7985704a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_15']/a</value>
      <webElementGuid>70b747c1-b49b-453c-b5ec-aa39800f3afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::a[1]</value>
      <webElementGuid>4d8722a3-ec8b-4ce6-9ad5-8e857472ea20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font'])[2]/following::a[1]</value>
      <webElementGuid>2e0a49c7-7b43-4794-acdd-fde112bc6257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text Color'])[1]/preceding::a[1]</value>
      <webElementGuid>c4cdcf40-256e-41cf-8eea-26718f804f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:void('Font Size')&quot;)]</value>
      <webElementGuid>1737c02d-3d50-4018-bd75-2ad6e487e0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/a</value>
      <webElementGuid>63ce0c56-55d5-4fef-9fea-d1211ca828bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Font Size' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Font Size&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Size' or . = 'Size')]</value>
      <webElementGuid>b4026b35-18fb-4810-9459-6854cb4ee63d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
