<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Strikethrough</name>
   <tag></tag>
   <elementGuidId>09499e6d-28fa-49e1-a0f2-4b57e160f906</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cke_24</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cke_24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e62a9df8-84b0-4d52-b313-5cb36d5610d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_24</value>
      <webElementGuid>3fc2c5db-951c-4efa-9a28-0085de6e1064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_button cke_button__strike cke_button_off</value>
      <webElementGuid>3f69b387-6b18-40ad-8781-9a00dcb13592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void('Strikethrough')</value>
      <webElementGuid>1fc800ce-0328-4b98-8f1b-20c2c958dd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Strikethrough</value>
      <webElementGuid>2b2753c3-4381-4528-8c40-3cddd371e069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>06e9c8ca-5cf3-481d-b979-0a5b73e40e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6835927e-f03a-4c7b-9a7f-1c707322dcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c5ebac0-456f-4225-8450-0fec577a47c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_24_label</value>
      <webElementGuid>1d3de4e5-5154-4f21-987f-d8e9b0a86302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cke_24_description</value>
      <webElementGuid>3a7b75a7-166f-483c-9b76-c96066f35ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f889364d-6b48-4029-b5eb-db8ecf9f6bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2fad5ebd-b67b-4390-8c14-036c06b7a6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(24,event);</value>
      <webElementGuid>df127e33-1ce0-43e1-9242-6e6bf46bc4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(25,event);</value>
      <webElementGuid>ee69fab6-05ec-48f9-b551-035fe75dfb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CKEDITOR.tools.callFunction(26,this);return false;</value>
      <webElementGuid>6ef30b05-7cd6-43a7-b6bb-cfa55beb1605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Strikethrough</value>
      <webElementGuid>fed2d142-4dc8-433b-bc25-24fa0b5b8ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_24&quot;)</value>
      <webElementGuid>fda74cf2-8477-43fd-b65d-aeda3dfb87ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>15052b42-62ac-478f-a36f-c50e0d84f31d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cke_24']</value>
      <webElementGuid>9412421e-3044-49d2-ae8a-349b517dc332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_16']/span[3]/a[8]</value>
      <webElementGuid>e6442d74-a412-4227-b2ba-bf20fdf590ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underline'])[1]/following::a[1]</value>
      <webElementGuid>7ae066be-0226-4848-a6f3-b1790e62874a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font'])[1]/preceding::a[1]</value>
      <webElementGuid>7549a365-83c0-4eb7-bb13-c7c2eeaeb96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:void('Strikethrough')&quot;)]</value>
      <webElementGuid>2182107f-f4c0-429f-b270-efe21da0bdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]</value>
      <webElementGuid>0e4434cc-ac85-48d0-b057-a4a1be3b81c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cke_24' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Strikethrough&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Strikethrough' and (text() = ' Strikethrough' or . = ' Strikethrough')]</value>
      <webElementGuid>a8977e6c-4e8a-4edc-b2aa-4ee7f9e4f849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
