<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Text Color</name>
   <tag></tag>
   <elementGuidId>f7f986f8-44b5-4835-b064-e7414b1a9b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cke_25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cke_25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1e6e9f1-a3b1-49b7-81e4-4cbcd643f4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_25</value>
      <webElementGuid>7b2acb5c-fdf8-46a5-a448-6f5f48e7ed33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_button cke_button__textcolor cke_button_expandable cke_button_off</value>
      <webElementGuid>81a7bad5-5aae-4986-b0c6-db0b7a080049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void('Text Color')</value>
      <webElementGuid>a496ccb7-3ced-4997-ae85-893cf456fede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Text Color</value>
      <webElementGuid>434df04b-6995-47c3-bdb9-ffddf8081b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a627ca57-4546-481c-aa3a-e1112cb0721d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>397117d8-3e88-4059-9744-0eb0e3130502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93f74c57-8f76-4496-9335-2576ed5fd2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_25_label</value>
      <webElementGuid>ae29aa07-a4a8-4f12-8ea9-9a64350e5cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cke_25_description</value>
      <webElementGuid>d6036bb9-4bf0-4baa-9d1a-14bd6dfecd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>79aeecfd-72ff-4af8-810f-93b573021e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98a35cb6-2bd2-4e47-9938-ff6fe4f7a235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(33,event);</value>
      <webElementGuid>fa0dac9c-04c0-4eb0-85e8-b82bd560d22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(34,event);</value>
      <webElementGuid>d5f5a2fe-acbe-4b45-a592-cde9822391c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CKEDITOR.tools.callFunction(35,this);return false;</value>
      <webElementGuid>16356370-684e-4d1a-a06d-9f212b628657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e472d4c4-5071-4cfd-8664-8e59da87dcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Text Color</value>
      <webElementGuid>a4c06e32-8c85-4e8e-ae99-78477a3273a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_25&quot;)</value>
      <webElementGuid>5e5bbc19-3dcd-4be1-b04f-bb0b84cf6407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>4b46b1a8-dd3c-44d7-9cd1-8a9447a8f72a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cke_25']</value>
      <webElementGuid>ec295fb4-5891-43ca-9755-91ba6bec9bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_16']/span[7]/a</value>
      <webElementGuid>c3a9eeb7-bcca-435a-a775-47760c44c9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[2]/following::a[1]</value>
      <webElementGuid>77834230-fbbc-418e-90ba-e4b0d3c860fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::a[2]</value>
      <webElementGuid>8061ea52-4de4-4cc5-b57b-73c00251fe4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Background Color'])[1]/preceding::a[1]</value>
      <webElementGuid>6bfbf691-cf10-4e91-8b1b-db06c64760d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:void('Text Color')&quot;)]</value>
      <webElementGuid>0f1288f7-9264-43a0-986a-3ca47ae8c6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[7]/a</value>
      <webElementGuid>6792e5c1-c457-47da-ab9b-5884b00a8b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cke_25' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Text Color&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Text Color' and (text() = ' Text Color' or . = ' Text Color')]</value>
      <webElementGuid>fad43520-3038-47ae-b80e-79aa4c537ab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
