<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_UnderlineKeyboard shortcut CtrlU</name>
   <tag></tag>
   <elementGuidId>93ddbb55-cd92-4d1f-8bed-a20bb85ec265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cke_23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cke_23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7b9d1fb-32a4-4f31-81d4-de45fec4db1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_23</value>
      <webElementGuid>605295c4-d387-4ba3-b9c5-62e0f3649eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_button cke_button__underline cke_button_off</value>
      <webElementGuid>1755336a-7a35-481d-8c1a-d427cc92cf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void('Underline')</value>
      <webElementGuid>cfdcafc1-df33-4927-a751-d0dc0b99f15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Underline (Ctrl+U)</value>
      <webElementGuid>1dd5769e-4a47-4f80-9bba-8eb9b22766e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>67469b7e-c576-4f83-9851-45a719c421bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>509d762d-f7a1-4278-a038-cf4faa02cd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>605d65dd-1568-435d-8d6d-bd549c0758f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_23_label</value>
      <webElementGuid>d875e9cd-b918-424c-9d30-91d1fb7fa04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cke_23_description</value>
      <webElementGuid>ed992864-c766-45c4-affa-f11452ac7e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f04f192e-8c74-4888-8818-4b328fc0ad7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c165279-0561-45d9-b424-dfc5566b2f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(21,event);</value>
      <webElementGuid>8e554273-86b3-4808-9b37-bf8de7ac4b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(22,event);</value>
      <webElementGuid>8e84c46f-38e1-40a9-b9a3-c16b247a7aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CKEDITOR.tools.callFunction(23,this);return false;</value>
      <webElementGuid>c8a59fec-ad45-4f88-ae3e-b0af2cf9dfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Underline Keyboard shortcut Ctrl+U</value>
      <webElementGuid>83c060d7-a060-4411-b8f8-4c5f95fac7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_23&quot;)</value>
      <webElementGuid>1654954d-41ff-4856-a93a-3886e0f1481a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>fa45348f-4ce3-4289-9048-e344be495123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cke_23']</value>
      <webElementGuid>5ee27c20-59e2-4f8f-af76-c2db19c2e8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_16']/span[3]/a[7]</value>
      <webElementGuid>4886ba75-d1fe-4045-b7b2-367d9fa62aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italic'])[1]/following::a[1]</value>
      <webElementGuid>a4661d16-10f6-4a1d-8bb5-e4675eef3712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:void('Underline')&quot;)]</value>
      <webElementGuid>17fc281f-3a2d-46b5-b09f-806d93540104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]</value>
      <webElementGuid>3f89e482-de37-4994-a9bb-38b749df1223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cke_23' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Underline&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Underline (Ctrl+U)' and (text() = ' Underline Keyboard shortcut Ctrl+U' or . = ' Underline Keyboard shortcut Ctrl+U')]</value>
      <webElementGuid>cbdfdd13-e3b6-44dd-9c7d-c5cb2a3f2180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
