<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>5c5272fa-b4e0-4b46-83ac-797a7cc0ec70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='186859af-9f4a-4c35-8341-6895e7199cc6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#186859af-9f4a-4c35-8341-6895e7199cc6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd3e8e1b-8d23-4ab7-a5fa-e3573206d5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>96937531-c01a-4749-87b5-ebafec289d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>186859af-9f4a-4c35-8341-6895e7199cc6</value>
      <webElementGuid>25344b67-6d2a-47e5-9067-5a957c181680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>903398cd-acb2-46c7-88f6-899cfbfc76c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;186859af-9f4a-4c35-8341-6895e7199cc6&quot;)</value>
      <webElementGuid>fa7a71fb-7006-48b9-be9f-26256d51cd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>e0b61109-dd79-4a7c-879d-f7d0efc8904d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='186859af-9f4a-4c35-8341-6895e7199cc6']</value>
      <webElementGuid>2715f7bc-9be3-4c71-bb41-7835adabad97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='181e9473-a794-4c7d-ac6e-f4fe15a2f1e9']/div/div/div[3]/div/div/button</value>
      <webElementGuid>71a6cba1-7c74-4b0b-9e9f-76c3424e777e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event invitation has been added successfully.'])[1]/following::button[1]</value>
      <webElementGuid>6cdca020-56fe-4034-9a59-617854ba644f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>d0d31ca6-bcb2-4bb4-ba4d-b56ec4ff6086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>b7e666ed-4a09-49cd-83ef-d3493afe913d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>8d23fa61-4a9e-4914-889a-573d91245478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '186859af-9f4a-4c35-8341-6895e7199cc6' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>71a39832-ab8d-4f07-a549-425aecc8cd37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
