<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__cke_285_frame</name>
   <tag></tag>
   <elementGuidId>097f6cf6-da08-49f8-8629-783f7648c3eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cke_285_frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cke_285_frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>de03adfb-cd31-4d16-8aa6-fae052cc32c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_285_frame</value>
      <webElementGuid>b7566c14-4ba4-4070-b027-fbb0fd9d789f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_panel_frame</value>
      <webElementGuid>99edad25-605d-477f-bb44-9228ef98f508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7e0dc269-90ec-48c2-980c-b07780904706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9b8570c2-f81c-46cc-8bb7-4bc0115ef3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_285_frame&quot;)</value>
      <webElementGuid>5f564971-bbbf-4ee3-9a22-54c71de4cfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>e840837b-a1ba-443e-a37f-cc44c4779ee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cke_285_frame']</value>
      <webElementGuid>9d68f58a-6568-445a-875a-d6eb203e5418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cke_285']/iframe</value>
      <webElementGuid>b3b1d5c2-6b5e-49c9-9c51-650f0de7cd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/iframe</value>
      <webElementGuid>fe806e6d-193f-46c9-bf71-5973597fd46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'cke_285_frame']</value>
      <webElementGuid>db8bca45-73cd-4571-b52b-f42febbbfa92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
