<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__cke_421_frame</name>
   <tag></tag>
   <elementGuidId>cffdd090-d7d5-4b76-8630-1e150c0a292a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cke_421_frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cke_421_frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4d2ea8dc-07f6-4363-bcbe-46746b7a27ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_421_frame</value>
      <webElementGuid>b5824923-f46d-4c3f-82c9-631ba054898e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_panel_frame</value>
      <webElementGuid>9eee4446-3164-410a-9742-86ce8d28ff96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>3d022bf0-08b2-4a0f-8695-fba4dfbc48c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fecdf235-b49b-4d86-9231-844a11621d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_421_frame&quot;)</value>
      <webElementGuid>3133db7c-c889-4ac1-8fa4-0498f11a6a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>26f099d1-d6a3-4632-a92b-e3d2de293e8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cke_421_frame']</value>
      <webElementGuid>dee4dedc-1206-49f3-b59e-ef82215a3bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cke_421']/iframe</value>
      <webElementGuid>8fe4811b-9746-431a-ade8-699a1291b334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/iframe</value>
      <webElementGuid>7abab590-3fe5-4531-9371-9c5cee3889ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'cke_421_frame']</value>
      <webElementGuid>e5a9f576-b017-47c9-acae-ecd2458f5f09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
