<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Emails for non-employees_sendEmailToNonEmp</name>
   <tag></tag>
   <elementGuidId>0ca0eab4-7530-4012-a633-3abd2ed0029a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sendEmailToNonEmp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sendEmailToNonEmp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a7951e0-c1b5-4330-b82a-b59680c9fe32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4fba51df-9baf-4845-83fb-774fba732410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sendEmailToNonEmp</value>
      <webElementGuid>78425ef1-f6f6-4ae4-998d-d7cd3491cc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:showHideEmailToNonEmp();</value>
      <webElementGuid>56f57a9e-3108-4e3d-80ad-7fe74a266a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendEmailToNonEmp&quot;)</value>
      <webElementGuid>d3998cbe-c0d1-48ba-aaea-b20c36e9d6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>79428fb1-0f2f-407e-b210-f2138a413b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sendEmailToNonEmp']</value>
      <webElementGuid>0acfebe8-856e-4a3a-a8e5-8a578ea0a805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[19]/label/input</value>
      <webElementGuid>09ae2443-f080-4d54-ac7d-483267e961aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/label/input</value>
      <webElementGuid>c0964fa5-57a8-4d8e-9811-65cfc00075a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'sendEmailToNonEmp']</value>
      <webElementGuid>d95818f3-3420-4b4e-b281-58ae152b20a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
