<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multi-day Checkbox</name>
   <tag></tag>
   <elementGuidId>277783c3-aaae-428d-bf23-251247a0aa9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiDayEvent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='multiDayEvent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e2103aa-8994-47be-9907-7b7456a3bea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>001acd0a-53e5-4a33-81df-836584cc0c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiDayEvent</value>
      <webElementGuid>4cd14b54-34bc-4876-8a0c-f64802307b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enableDisableDateTimeBox(this);</value>
      <webElementGuid>fda67814-36b6-49ac-9f49-d377ea8e078e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiDayEvent&quot;)</value>
      <webElementGuid>124b4233-ff59-418d-8340-12fcff4e08c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>e8ee1a54-3ce0-40ba-9d89-59ee17dcecd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='multiDayEvent']</value>
      <webElementGuid>187186e9-4b8e-4b35-be8a-212a7e2e2e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[2]/div/input</value>
      <webElementGuid>09bf4904-cd87-41f5-9645-0ed77c13bff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>50d18fe9-73f7-43a9-8115-b21bd08e8468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'multiDayEvent']</value>
      <webElementGuid>a4a17891-30a5-4f0b-9fdd-1ec2bfe143ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
