<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Daily_frequency Radio Button</name>
   <tag></tag>
   <elementGuidId>115eddd9-9072-4d7d-b701-3f638a1debce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;frequency&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='frequency']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'frequency' and @value = '${frequency}' and @ref_element = 'Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28180a84-d7f2-4d3a-85b5-b86457415315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f80858ad-aa16-4a2e-b635-f3238b790e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:showHideSelectionOfRepetition();</value>
      <webElementGuid>cfe170e4-ae41-4ebd-84a8-4e3d1e5a5f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frequency</value>
      <webElementGuid>1c1b03e7-70ea-46df-9a47-7e898e157173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frequency</value>
      <webElementGuid>6f23cd58-ade5-4d5d-8030-dbb0023de2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${frequency}</value>
      <webElementGuid>eeabea4a-b392-4e3b-a1c8-c409e56217dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeteSection&quot;)/div[1]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;col-md-3 form-group&quot;]/input[@class=&quot;frequency&quot;]</value>
      <webElementGuid>85f8256c-10e9-4921-a382-77b984da1308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>d9cc7355-1327-4684-9b9a-76499e6efadf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='frequency']</value>
      <webElementGuid>d1e75e36-a6ff-488c-899a-ad736064ae22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeteSection']/div/div/div/input</value>
      <webElementGuid>576a0ac1-3d08-402a-91b4-409381a6d7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/input</value>
      <webElementGuid>407f3556-fb9e-4476-aae5-8ac8cc29d42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'frequency']</value>
      <webElementGuid>6ee68571-40b6-4ab0-8536-1c8570e2c03c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
