<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add this event on my calendar also  Checkbox</name>
   <tag></tag>
   <elementGuidId>37a24442-2250-4dcf-aff6-ea0100b20255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addEventToMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addEventToMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c505f26d-471b-43b5-ae2f-b374b404664c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5de20647-c14c-4ade-82b1-1b1d0193dc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addEventToMe</value>
      <webElementGuid>29968382-ae81-4b6e-a018-5af6f071841b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addEventToMe&quot;)</value>
      <webElementGuid>80c674c3-d465-4bf1-8004-42ecb1560064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>89efc1c2-b5bb-4016-87fb-98a1376643d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addEventToMe']</value>
      <webElementGuid>a2e77f8b-baca-4477-adb8-5f56f0c1c4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[4]/div[3]/input</value>
      <webElementGuid>0da86d33-cb81-45a7-b274-c9fe2ef4abfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>69a2ceaa-862b-4688-bab4-7092b6f00baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'addEventToMe']</value>
      <webElementGuid>5e93e58b-d6d0-4754-8578-8187c3156be1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
