<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start date_date_selectedStartDate</name>
   <tag></tag>
   <elementGuidId>7168000a-1b09-468c-86d8-2ab3f1fe2f89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedStartDate']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'selectedStartDate' and @value = '${startDate}' and @name = 'date_selectedStartDate' and @ref_element = 'Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0663ad82-dcaf-4329-941b-e3841d616b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f0325c2-f835-425e-8818-62fa2be39c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedStartDate</value>
      <webElementGuid>2436d210-4dd0-475a-8f37-04493d5ce5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${startDate}</value>
      <webElementGuid>a5b292e9-375a-4c8e-b193-e99f54fa756f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_selectedStartDate</value>
      <webElementGuid>cf683f80-232f-41d8-8c79-7f8fd2d07fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>3a0a78f0-dc65-42f5-ab72-46d4e5c77643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedStartDate&quot;)</value>
      <webElementGuid>9681354a-11df-48ad-a774-af03d52ef02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>35885b6f-cd64-4200-84ff-e125a369e0e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedStartDate']</value>
      <webElementGuid>03549b39-3235-4cf0-813b-877928fc6ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[7]/div/input</value>
      <webElementGuid>13784f0c-d64f-4582-a11c-b14059912ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[7]/div/input</value>
      <webElementGuid>02abd57e-b695-44ab-9262-b2aede115c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectedStartDate' and @name = 'date_selectedStartDate']</value>
      <webElementGuid>21d5dcca-dab0-4c0c-b0af-43489bc99382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
