<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Private  Checkbox</name>
   <tag></tag>
   <elementGuidId>5dd6cee8-21c6-474b-9984-c800b78a4b89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isPrivateEvent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isPrivateEvent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d67685c4-8a36-49b5-9b43-fb31406e7b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eafc5a46-6ced-4876-b1e4-65ca06514fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isPrivateEvent</value>
      <webElementGuid>bdd9f862-479e-46d6-a3bc-d453c429501b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isPrivateEvent&quot;)</value>
      <webElementGuid>19f30d05-7690-4ee9-891f-370202d7825b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>fc6f7049-cce4-4945-a4c1-77cbe85487a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isPrivateEvent']</value>
      <webElementGuid>394e00ea-6103-4edf-bcc5-19751aee2229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[4]/div[2]/input</value>
      <webElementGuid>aec454b6-ed3b-469f-b806-cd4011d7f695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>0702e114-e6dd-4b83-b416-47f8ad3375d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isPrivateEvent']</value>
      <webElementGuid>07dbbbf2-75f0-4fab-867b-70189a8e8df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
