<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repeat Checkbox</name>
   <tag></tag>
   <elementGuidId>1ef36b5d-a180-4519-b03d-b725437b2311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isRecurring</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isRecurring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f643684e-2016-48a1-adb2-403cf0976d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6235185d-43ca-4891-97e1-8f78ae5ff03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isRecurring</value>
      <webElementGuid>765957a5-4bd3-4d5a-b6fe-8982d441831a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showHideRepeatSection(this);</value>
      <webElementGuid>b212c6a3-729d-411e-aa64-73bb4bdc13d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isRecurring&quot;)</value>
      <webElementGuid>01f64589-92c9-439f-a452-369e263599e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>26fa7685-6af8-45fb-b2b9-26c70be6bd28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isRecurring']</value>
      <webElementGuid>d366d461-1f29-4f89-9642-0a89ce5d54db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isRecurringDiv']/div/input</value>
      <webElementGuid>8e60c4ae-29a0-440c-8851-d58bbe82f9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/input</value>
      <webElementGuid>0ba366b9-9416-44cd-8e6c-13a42099badd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isRecurring']</value>
      <webElementGuid>9aad0326-e515-4157-9bd8-2cce7c999d4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
