<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_All day event Checkbox</name>
   <tag></tag>
   <elementGuidId>408439c0-f95c-4a8a-9910-6f87a786c4e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#allDayEventMode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='allDayEventMode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>374cc866-b80f-4e99-83c6-c2e0a7e23205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b53369c9-0367-4995-a1ce-d6034068f44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allDayEventMode</value>
      <webElementGuid>bba56a39-6c14-4447-83af-c0ffe070f68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enableDisableTimeDurationBox(this);</value>
      <webElementGuid>b86b94bb-0a83-4e51-92da-20444bbe522f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allDayEventMode&quot;)</value>
      <webElementGuid>578697e1-ab49-476c-9e75-0f20683f3f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>bfe9a90b-b769-4d27-95ba-4675687272da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='allDayEventMode']</value>
      <webElementGuid>05c8c170-f3d2-4014-985f-6f48fcda4036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allDayEventDiv']/input</value>
      <webElementGuid>d4c705ff-c40e-436a-9002-e8b368060749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/input</value>
      <webElementGuid>abd7d2a0-d86d-450f-b25d-5f9f4471cefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'allDayEventMode']</value>
      <webElementGuid>e0175603-9896-4f1b-bf0a-3191868a8a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
