<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Repetition Daily</name>
   <tag></tag>
   <elementGuidId>8ca00913-e4d1-4562-a428-c8558a7096c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repetitionDaily</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='repetitionDaily']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce241f5a-5fcf-416d-9feb-60983a9f5004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repetitionDaily</value>
      <webElementGuid>6e0085a6-1997-49c6-bb1c-ce6f16953af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control frequencyValue</value>
      <webElementGuid>46303f2c-60ca-4b72-9d2e-abf4eddee01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---23456789101520304560</value>
      <webElementGuid>c8428b15-cd84-42a9-8b4c-1a748f87f799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repetitionDaily&quot;)</value>
      <webElementGuid>67d7e346-270c-4805-b379-4ccea7c17951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>a602d1b0-2157-4dfb-aaab-1c0f6866771a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='repetitionDaily']</value>
      <webElementGuid>f59340d3-8d94-4e14-82ca-bccca8fda230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repetitionDailySection']/div/select</value>
      <webElementGuid>aa31b770-2c8a-47ce-9546-7ccec936c1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repetitions'])[1]/following::select[1]</value>
      <webElementGuid>988174b9-45b1-4afd-ad03-6658cc690240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendees'])[1]/preceding::select[3]</value>
      <webElementGuid>dec9c01f-a514-44ea-a262-10b4fe7b987e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>6b6475c5-acd5-46d9-b07d-90d8f16dbc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'repetitionDaily' and (text() = '---Select---23456789101520304560' or . = '---Select---23456789101520304560')]</value>
      <webElementGuid>7e92c230-f1f8-42b1-a17c-a5cef341253c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
