<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AMPM End Time</name>
   <tag></tag>
   <elementGuidId>c23a78a9-bbb2-4445-9b84-ab4d447f5b76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endTime_ampmOptions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='endTime_ampmOptions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9d1fbda4-10f1-49da-85d9-39acd399c022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endTime_ampmOptions</value>
      <webElementGuid>5cdef28f-6642-478c-8c4b-8672b78cbc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>87f971e0-c7ad-4aaa-8af2-0b20d3f968e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMPM</value>
      <webElementGuid>c3ccba4e-4e40-4fbf-aeff-3951388cda6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endTime_ampmOptions&quot;)</value>
      <webElementGuid>2bb9b5d7-d583-4da0-acc8-dc2161ba93af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (4)</value>
      <webElementGuid>10de6cdb-c79e-4401-a52d-145fb048ba2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='endTime_ampmOptions']</value>
      <webElementGuid>0643822a-61f3-40f0-be8b-1534f5a356f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='endTimeDiv_ampmOptions']/select</value>
      <webElementGuid>e24dc5c7-b94d-4b6e-8667-2f85796dc5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End time'])[1]/following::select[1]</value>
      <webElementGuid>b7c00ddc-58dd-49f1-beb4-cca50b398eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[1]/following::select[1]</value>
      <webElementGuid>ad9f0737-9bac-4798-916e-6fa99541ea6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/preceding::select[1]</value>
      <webElementGuid>b4f7e62a-57f6-456d-b5d4-9be19c9625df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/preceding::select[2]</value>
      <webElementGuid>37f7cf17-e97f-4f29-b369-ce330b1fdbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/select</value>
      <webElementGuid>152b9d40-1f68-42d6-9677-8411492d1043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'endTime_ampmOptions' and (text() = 'AMPM' or . = 'AMPM')]</value>
      <webElementGuid>8785cae1-ebe2-4e9a-b19a-291ea16e586a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
