<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select---15 Minutes30 Minutes45 M_45c030</name>
   <tag></tag>
   <elementGuidId>c1029306-2a45-4eea-a9fb-1a13f69c07f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='duration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#duration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>80f9e041-56bb-44a4-8fbc-1415fb2ca06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>8d285521-f5b5-436e-b371-32b0eea688a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2d8a38cf-4ffa-4b77-befa-7184419c87be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour</value>
      <webElementGuid>51f1d081-5f27-421e-9d3f-cb0f0e8afd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;duration&quot;)</value>
      <webElementGuid>f27fb0c6-a3b3-40c7-baf9-faf5a3f3065f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>33447fbd-4702-4fe2-ac46-f5dedb6aacee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='duration']</value>
      <webElementGuid>fc21bfdc-27eb-46d9-99c1-d650b4190c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='durationDiv']/div/select</value>
      <webElementGuid>43a1d58e-aece-42f7-ac8a-304f43eb95f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[1]</value>
      <webElementGuid>7fce3ea8-1778-4e22-bdf0-cf32871a255e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End time'])[1]/following::select[2]</value>
      <webElementGuid>2ff112b3-e40a-4ebf-87df-3a102b74c3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/preceding::select[1]</value>
      <webElementGuid>f8e586a2-b45d-44ff-9edf-21d71771a9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/select</value>
      <webElementGuid>e650ceb1-19e5-4760-9819-a89bc0db5e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'duration' and (text() = '---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour' or . = '---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour')]</value>
      <webElementGuid>2e92b602-ecb1-44b0-9cfe-7421fa2af82d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
