<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Time Zone Multi-day Event</name>
   <tag></tag>
   <elementGuidId>e325f837-7fce-4b4d-a5be-36fc13b6f608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timeZone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='timeZone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9b895fe7-0748-4c88-91f0-1180268460c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timeZone</value>
      <webElementGuid>ef4617ed-38bc-4fa1-b7b3-771bb9c30e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d42355f7-ec2a-47e3-986e-d615bfbdbe09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi</value>
      <webElementGuid>bbee0e2b-2f55-4362-886d-f2b0b8060c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeZone&quot;)</value>
      <webElementGuid>74fe0b49-c6b8-41c4-9703-775943eab949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (4)</value>
      <webElementGuid>4d36517e-0668-4946-847c-7e93c790ca2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='timeZone']</value>
      <webElementGuid>fb392545-8556-4316-9ecb-0feb264e907d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[13]/div/select</value>
      <webElementGuid>11e8297f-d269-4c2e-a62b-9646d7402bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/following::select[1]</value>
      <webElementGuid>2b4f619e-eb04-4801-a00d-c7d0873b94ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[2]</value>
      <webElementGuid>03af2f07-61a1-414f-96b3-82771e625610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency'])[1]/preceding::select[1]</value>
      <webElementGuid>ecfb9941-6390-41b3-a9b5-7cfbd66fe130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/select</value>
      <webElementGuid>8b0ae6bb-27cd-426d-8c3a-e8a54ccd59a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'timeZone' and (text() = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi' or . = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi')]</value>
      <webElementGuid>4738ac1a-2a96-47d3-b5a1-eb9c837b53d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
