<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Repetition Monthly</name>
   <tag></tag>
   <elementGuidId>436280e3-8457-4ff4-8336-fe88223c2e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repetitionMonthly</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='repetitionMonthly']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d3f59145-a751-4023-8ae1-afd232eb6139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repetitionMonthly</value>
      <webElementGuid>96ad6d90-b431-4a92-9afa-1f064a56e71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control frequencyValue</value>
      <webElementGuid>796f388c-10f3-4fa4-b8f5-d940151652b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---23456789101112</value>
      <webElementGuid>86159827-8872-4e79-a094-f97ab9ee62cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repetitionMonthly&quot;)</value>
      <webElementGuid>167a54a3-d341-492b-8241-0fd41fbb8339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>9c1b5858-3d6b-4b91-b0fd-a9847b337edd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='repetitionMonthly']</value>
      <webElementGuid>e8bf7ce3-70ef-4095-99d9-cf990e431840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repetitionMonthlySection']/div/select</value>
      <webElementGuid>704efacc-3bee-4944-82c9-8c4da34140e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repetitions'])[1]/following::select[3]</value>
      <webElementGuid>7c229383-305b-4cc5-ab58-65c441fd0960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendees'])[1]/preceding::select[1]</value>
      <webElementGuid>742a793d-b950-4f68-828c-61849b242598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>584169d9-46f8-449c-9586-48659d66589d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'repetitionMonthly' and (text() = '---Select---23456789101112' or . = '---Select---23456789101112')]</value>
      <webElementGuid>19ac4c5f-9b8c-4d5e-82b4-b3c9fac0c0e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
