<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Automatic_cke_colorbox</name>
   <tag></tag>
   <elementGuidId>73bd94ac-a8b5-4198-8d52-f14c7080d5f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/table/tbody/tr[2]/td[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84c00b1e-9079-4208-9ffb-757edc999fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_colorbox</value>
      <webElementGuid>2a1ad1c5-92d3-4a31-81b0-18919967405a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cke_panel_container cke_browser_webkit&quot;]/body[@class=&quot;cke_ltr&quot;]/div[@class=&quot;cke_panel_block cke_colorblock&quot;]/table[1]/tbody[1]/tr[2]/td[5]/a[@class=&quot;cke_colorbox&quot;]/span[@class=&quot;cke_colorbox&quot;]</value>
      <webElementGuid>98bc682b-02fc-4f8c-a963-0fdc281ab05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/Page_Home page/iframe__cke_421_frame</value>
      <webElementGuid>ee63ed1d-164e-4984-9b83-46de22d90b1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[2]/td[5]/a/span</value>
      <webElementGuid>baef9052-6351-4625-b18b-8df1d4b11b8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
