<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_An email has been sent to the email id _cbbc3a</name>
   <tag></tag>
   <elementGuidId>e20b5afa-8df4-41f6-9604-57d08000ad6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#m16_errorMsgOnPopUpEmploginProblem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e50328be-ede9-4503-9af0-72b0f193f2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>succ</value>
      <webElementGuid>7e7b6648-fa65-4587-b144-f3dfc50d62d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m16_errorMsgOnPopUpEmploginProblem</value>
      <webElementGuid>d5b394de-bb4d-470b-ba2c-62c5e786e814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>An email has been sent to the email id for the user name. This will help you in resetting the password.</value>
      <webElementGuid>3e0fdb3f-8f8b-4306-b27b-4d4b7a8ec7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m16_errorMsgOnPopUpEmploginProblem&quot;)</value>
      <webElementGuid>f1ac386c-30a4-4ff8-884d-fbd422c45b5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      <webElementGuid>00570966-5d5a-49bd-8c2f-78a9f8e324d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='errorMsgOnPopUpEmploginProblem']/div</value>
      <webElementGuid>293513f7-0c61-42d6-95e5-791582e19ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login problems'])[1]/following::div[2]</value>
      <webElementGuid>8e1be0d3-3cbc-4058-bc1c-c811fd6ae111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © Saigun Technologies Pvt. Ltd. India. All rights reserved. Confidential'])[1]/following::div[9]</value>
      <webElementGuid>a5df64d9-7008-49c7-82bc-9d57f7129627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='An email has been sent to the email id for the user name. This will help you in resetting the password.']/parent::*</value>
      <webElementGuid>887a8011-6142-464b-bd56-9f52641130b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>bed887f4-dfe8-453f-a9bd-f1bd88d47681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'm16_errorMsgOnPopUpEmploginProblem' and (text() = 'An email has been sent to the email id for the user name. This will help you in resetting the password.' or . = 'An email has been sent to the email id for the user name. This will help you in resetting the password.')]</value>
      <webElementGuid>2b205ee1-0d3b-4e8b-9a3f-63fb6f5baf18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
