<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Company ID (tenant) is not recognized</name>
   <tag></tag>
   <elementGuidId>c05b8293-6577-4d36-ba8b-e19ae598ac8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#m16_errorMsgOnPopUpEmploginProblem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>085f1363-4e9f-4114-a9cf-49c40820b237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>err</value>
      <webElementGuid>ce7c0884-e8f9-4827-8d37-491224f7f0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m16_errorMsgOnPopUpEmploginProblem</value>
      <webElementGuid>5f158cdc-bfb8-46b1-a5e3-e33a9734db74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company ID (tenant) is not recognized.</value>
      <webElementGuid>dafde0b2-cdd2-4d98-825d-03a207ce2283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m16_errorMsgOnPopUpEmploginProblem&quot;)</value>
      <webElementGuid>d3754545-13cc-4c4e-9dee-f8d9fd1e0eaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      <webElementGuid>22556257-48ef-40b8-9701-61cdc22b6f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='errorMsgOnPopUpEmploginProblem']/div</value>
      <webElementGuid>73069ec4-dc53-43bb-8300-e71a7186033c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login problems'])[1]/following::div[2]</value>
      <webElementGuid>73a1ce0d-603c-423f-93e5-9233c305ca2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © Saigun Technologies Pvt. Ltd. India. All rights reserved. Confidential'])[1]/following::div[9]</value>
      <webElementGuid>aab4ba58-446a-4da0-a940-e0835b8bc2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company ID (tenant) is not recognized.']/parent::*</value>
      <webElementGuid>7a9338f2-9069-4a14-8732-d63098885bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>6074c3a8-179f-46f8-9fe2-420597fb8705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'm16_errorMsgOnPopUpEmploginProblem' and (text() = 'Company ID (tenant) is not recognized.' or . = 'Company ID (tenant) is not recognized.')]</value>
      <webElementGuid>0ea77c6f-ce85-43a3-88c5-8da32586840e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
