<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User Name is not recognized</name>
   <tag></tag>
   <elementGuidId>cdaa85ab-f676-4d00-8658-ec8e07148f20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#m16_errorMsgOnPopUpEmploginProblem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34534443-aad0-496d-b463-7d8c69744ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>err</value>
      <webElementGuid>ad601da2-c0ed-4722-903d-c4434c5ad9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m16_errorMsgOnPopUpEmploginProblem</value>
      <webElementGuid>5d51c2cd-58de-4cf0-819d-68e195ecd826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name is not recognized.</value>
      <webElementGuid>738f95cf-ecb8-4b76-bd0b-c82660e41373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m16_errorMsgOnPopUpEmploginProblem&quot;)</value>
      <webElementGuid>84bd644e-258e-44c2-8005-f20a052a9156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      <webElementGuid>3869c653-8b99-4399-8131-a458d4c034d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='errorMsgOnPopUpEmploginProblem']/div</value>
      <webElementGuid>882c1169-0b9a-433c-8c66-41beebb1e6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login problems'])[1]/following::div[2]</value>
      <webElementGuid>10ab42a9-794b-4895-bf42-a959bcd9d73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © Saigun Technologies Pvt. Ltd. India. All rights reserved. Confidential'])[1]/following::div[9]</value>
      <webElementGuid>9a7e1602-d2e4-4067-b6fd-a24c6db9fe97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Name is not recognized.']/parent::*</value>
      <webElementGuid>ed8eb287-1228-4a95-87b9-d4adcad9c63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>8433a7f4-30aa-46a9-b952-48f3604ce13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'm16_errorMsgOnPopUpEmploginProblem' and (text() = 'User Name is not recognized.' or . = 'User Name is not recognized.')]</value>
      <webElementGuid>ae455f8f-3c5d-434e-a36c-85f609b169f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
