<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View in full page</name>
   <tag></tag>
   <elementGuidId>d09ca9cd-462a-4a30-b5e9-b17ff3428ec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_View20in20full20page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_View20in20full20page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4454f835-3881-4ccc-98c3-c7de6335632b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_primary </value>
      <webElementGuid>af27f071-75e2-48dc-ade0-f0449ef68ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_View20in20full20page</value>
      <webElementGuid>98bb4f23-0d74-422a-a28c-56b746334d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>eb0244a6-41a2-4d03-bad0-8db7a79a344b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>displayURL('runet.do?activity=submit&amp;mod=MyTicketHelpDesk','');return false;</value>
      <webElementGuid>c8c497b7-f15d-4ac9-9249-abc27cbf87d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View in full page</value>
      <webElementGuid>810d0ebf-f3cc-4cdf-a81c-9dc561ed405f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_View20in20full20page&quot;)</value>
      <webElementGuid>6ba67a04-a37d-4b89-a25b-25287d91a7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/04 - Tickets/TC_052_ViewMyTicketFullPage/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>868f1fcb-d612-4ee2-835b-225f2967593e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_View20in20full20page']</value>
      <webElementGuid>dddaf2aa-f3cf-4de7-bb48-1aac2178fda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section-panel']/div/div/div[3]/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>b73f07b2-9421-402f-aaa7-8f2eb509e67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View in full page')]</value>
      <webElementGuid>916c2ddb-42c7-4023-90b0-21a1299b6966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create ticket'])[1]/following::a[1]</value>
      <webElementGuid>9c38eaea-c4cb-4a7f-8a71-c7fb901006cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[1]/following::a[2]</value>
      <webElementGuid>8ad69d7d-fc8a-4dfc-aaee-199e83462c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[1]</value>
      <webElementGuid>816767a7-bbfb-4ae5-8c70-6dc67f96f2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btn_View20in20full20page', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>b520da2f-f687-4cf3-b1f1-e0a097812f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View in full page']/parent::*</value>
      <webElementGuid>1ffc8ac0-bd65-429c-8821-32753c6f81a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>b2e8a8b0-b912-4fa6-8f6d-4106ebe060e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>fcbad502-a0eb-4e98-a6f2-51297744e6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_View20in20full20page' and @href = 'javascript:void(0);' and (text() = 'View in full page' or . = 'View in full page')]</value>
      <webElementGuid>33f17fb7-9cb8-45b3-98b7-ac6289a771fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
