<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_002_ResetPassword</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a83ffb95-47e1-4985-b22d-d1fcfd03764a</testSuiteGuid>
   <testCaseLink>
      <guid>2f5ce3b7-97a6-4cb4-8b3a-337791cfc0e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC02 - ResetPassword/01_Positive/TC_004_ResetPasswordSuccess</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62487ccf-91c3-4206-a0d2-ac4797bf1266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ba68592-28f0-4c4d-a9a6-dcdaf9c8f482</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca3da1b1-225f-4e21-8f08-77169601d26e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC02 - ResetPassword/02_Negative/TC_005_BlankInput</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62487ccf-91c3-4206-a0d2-ac4797bf1266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ba68592-28f0-4c4d-a9a6-dcdaf9c8f482</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
