<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave policy</name>
   <tag></tag>
   <elementGuidId>9da2ddc1-a74c-4ea1-b37b-f2ca3a66db83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Leave20policy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Leave20policy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b9618b4-5958-4fde-82ff-0039c31e54a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_secondary</value>
      <webElementGuid>47ee35a5-8954-4e3f-b826-4be2a9669e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Leave20policy</value>
      <webElementGuid>13c976c2-7eab-4f4d-b308-d85a551179fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>64d4f252-67f0-47f7-bcf0-8705fb83cf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showLeavePolicy();enableSelectedShortCut('ql_l.leave.leavePolicy');initToggleSliderShortCut()</value>
      <webElementGuid>f961b380-0cef-4c97-a420-4ce3b0465251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave policy</value>
      <webElementGuid>ba3dc794-3577-471e-bf34-32f1f3b5eac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Leave20policy&quot;)</value>
      <webElementGuid>f4371058-83eb-42cc-83d0-8c691608d93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/02 - Leave/TC_047_ViewLeavePolicy/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>f2e023ff-3da3-4de6-bff3-b978c6595166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Leave20policy']</value>
      <webElementGuid>796c3cc5-3cde-4da2-9ba7-e029b2015a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section-panel']/div/div/div[4]/div/div/a[3]</value>
      <webElementGuid>6df4f9a0-fcd5-4b7d-b2e1-5c80b1a8ca0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leave policy')]</value>
      <webElementGuid>568f6575-7c6a-440e-9dff-3cc899608ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave transactions'])[2]/following::a[1]</value>
      <webElementGuid>6943610b-cc42-45f7-8421-534db1e8305f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My leave'])[1]/following::a[2]</value>
      <webElementGuid>ed628b43-a79d-45fb-a8a9-f7f670e00692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Calendar'])[1]/preceding::a[1]</value>
      <webElementGuid>54da6e91-029d-420c-8ea6-3fc8dd358edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[2]</value>
      <webElementGuid>ae074cd5-90b6-41ff-8669-21bcca26246e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave policy']/parent::*</value>
      <webElementGuid>cbe81157-42e4-41ed-9857-82b7c873ba04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>a075d0d6-881c-4dbf-a485-3eb231ced5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a[3]</value>
      <webElementGuid>31494961-4116-4af0-9816-6fdc895a09b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Leave20policy' and @href = 'javascript:void(0);' and (text() = 'Leave policy' or . = 'Leave policy')]</value>
      <webElementGuid>0e29afde-0449-443b-8064-3c774bd8f34c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
