<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Help_fas fa-eye</name>
   <tag></tag>
   <elementGuidId>b64cc4e2-89ba-4d53-8b6c-5248dd1652a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_0']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9d5e585f-02c2-4da4-a355-646577ee188f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89bf6c94-0fd3-4663-9173-9cbeef6d0d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye</value>
      <webElementGuid>ffe3cd36-c01f-4b2e-9b20-c636f3569f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionItemsInSlideDropDownOptions&quot;)/a[@id=&quot;btn_0&quot;]/i[@class=&quot;fas fa-eye&quot;]</value>
      <webElementGuid>76726619-fed9-44ab-a702-181b5845d126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/01 - Profile/TC_044_ViewProfileChange/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>23fd45d5-b928-4a92-9266-cf1d8aec24d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn_0']/i</value>
      <webElementGuid>a34dd3c4-f9fb-4dc9-9de4-5fd57c84fe65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>68a5a832-b9e9-4bfa-b01e-124d738e703a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
