<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_014_Add Employee</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d5627fe1-942d-4173-8380-1386fc0cd678</testSuiteGuid>
   <testCaseLink>
      <guid>78399f0b-bc89-49f3-a01d-509b0d1dc140</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC07 - Employee List/01 - Add Employee/01- Positive/TC_038_AddEmployee</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>86bdb483-051b-43ec-bc5f-edbf73b8da97</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TC07 - Employee List/TD_004_AddEmployee</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empFirstName</value>
         <variableId>87fd92f0-f499-436a-8b86-752fafdaf050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empMidName</value>
         <variableId>583ee1b3-fcbb-44da-97db-84b224250df9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empLastName</value>
         <variableId>669f7601-49d6-4675-8bb7-ad00f8ff5b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empID</value>
         <variableId>15307e95-6a64-4fe9-977e-5ec935a82371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empUsername</value>
         <variableId>a6ed10c4-47ca-4643-9437-c1630dada7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empPassword</value>
         <variableId>30cfe9af-fba2-439a-9e0a-4706ce89f0e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>empPasswordConfirmaton</value>
         <variableId>3b2c31f0-0cb4-4986-9b2a-aeeb13ac32d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>a7f67bfc-f508-4a5f-9140-b3c8a4522bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86bdb483-051b-43ec-bc5f-edbf73b8da97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>file</value>
         <variableId>3f29ebdc-2a7c-4eef-9509-209e75798418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9766c3c6-022a-48f3-979e-2f8e657d750a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC07 - Employee List/01 - Add Employee/02- Negative/TC_039_UseExistingEmpID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87fd92f0-f499-436a-8b86-752fafdaf050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583ee1b3-fcbb-44da-97db-84b224250df9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669f7601-49d6-4675-8bb7-ad00f8ff5b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15307e95-6a64-4fe9-977e-5ec935a82371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ed10c4-47ca-4643-9437-c1630dada7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30cfe9af-fba2-439a-9e0a-4706ce89f0e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b2c31f0-0cb4-4986-9b2a-aeeb13ac32d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f67bfc-f508-4a5f-9140-b3c8a4522bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f29ebdc-2a7c-4eef-9509-209e75798418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bf9a062-5826-49bb-98df-8e524e4346af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC07 - Employee List/01 - Add Employee/02- Negative/TC_040_LargeFile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87fd92f0-f499-436a-8b86-752fafdaf050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583ee1b3-fcbb-44da-97db-84b224250df9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669f7601-49d6-4675-8bb7-ad00f8ff5b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15307e95-6a64-4fe9-977e-5ec935a82371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ed10c4-47ca-4643-9437-c1630dada7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30cfe9af-fba2-439a-9e0a-4706ce89f0e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b2c31f0-0cb4-4986-9b2a-aeeb13ac32d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f67bfc-f508-4a5f-9140-b3c8a4522bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f29ebdc-2a7c-4eef-9509-209e75798418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48aebeb4-ddf1-4cda-90ba-fc4147145017</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC07 - Employee List/01 - Add Employee/02- Negative/TC_041_ExistedUsername</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87fd92f0-f499-436a-8b86-752fafdaf050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583ee1b3-fcbb-44da-97db-84b224250df9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669f7601-49d6-4675-8bb7-ad00f8ff5b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15307e95-6a64-4fe9-977e-5ec935a82371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ed10c4-47ca-4643-9437-c1630dada7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30cfe9af-fba2-439a-9e0a-4706ce89f0e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b2c31f0-0cb4-4986-9b2a-aeeb13ac32d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f67bfc-f508-4a5f-9140-b3c8a4522bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f29ebdc-2a7c-4eef-9509-209e75798418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b97e3bc-2f82-4672-9e74-d9983ff82143</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC07 - Employee List/01 - Add Employee/02- Negative/TC_042_PasswordLessThan8</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87fd92f0-f499-436a-8b86-752fafdaf050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583ee1b3-fcbb-44da-97db-84b224250df9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669f7601-49d6-4675-8bb7-ad00f8ff5b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15307e95-6a64-4fe9-977e-5ec935a82371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ed10c4-47ca-4643-9437-c1630dada7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30cfe9af-fba2-439a-9e0a-4706ce89f0e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b2c31f0-0cb4-4986-9b2a-aeeb13ac32d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f67bfc-f508-4a5f-9140-b3c8a4522bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f29ebdc-2a7c-4eef-9509-209e75798418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5cf14490-b9f3-4d3d-93f7-029f47be99fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC07 - Employee List/01 - Add Employee/01- Positive/TC_043_PasswordVeryWeak</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87fd92f0-f499-436a-8b86-752fafdaf050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583ee1b3-fcbb-44da-97db-84b224250df9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669f7601-49d6-4675-8bb7-ad00f8ff5b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15307e95-6a64-4fe9-977e-5ec935a82371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ed10c4-47ca-4643-9437-c1630dada7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30cfe9af-fba2-439a-9e0a-4706ce89f0e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b2c31f0-0cb4-4986-9b2a-aeeb13ac32d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f67bfc-f508-4a5f-9140-b3c8a4522bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f29ebdc-2a7c-4eef-9509-209e75798418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01522da8-f605-4620-8d99-14e223034766</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC07 - Employee List/01 - Add Employee/02- Negative/TC_044_PasswordConfirmationWrong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87fd92f0-f499-436a-8b86-752fafdaf050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583ee1b3-fcbb-44da-97db-84b224250df9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669f7601-49d6-4675-8bb7-ad00f8ff5b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15307e95-6a64-4fe9-977e-5ec935a82371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ed10c4-47ca-4643-9437-c1630dada7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30cfe9af-fba2-439a-9e0a-4706ce89f0e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b2c31f0-0cb4-4986-9b2a-aeeb13ac32d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f67bfc-f508-4a5f-9140-b3c8a4522bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f29ebdc-2a7c-4eef-9509-209e75798418</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
