<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Out time_outTime</name>
   <tag></tag>
   <elementGuidId>6d0c47ac-4e79-4f4d-8e35-475b8cb51c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a4b809c-08be-4129-b6a5-4278bab85e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control timeText hasDatepicker</value>
      <webElementGuid>816ffa0b-7ced-402a-8cf7-7d24c7355a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd2f6934-fc33-46e6-a689-fd8f6f98771d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outTime</value>
      <webElementGuid>75a32051-5e42-4fb7-8f17-5cf6d6f09db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calculateHrs();</value>
      <webElementGuid>855db1a6-e99e-4830-98fa-3f7e1aedad1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17:00</value>
      <webElementGuid>53c3f4b2-8dc7-4a42-9bf2-856f169c6b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>20d3248b-6fe5-4308-8b1d-705ac1e717af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outTime&quot;)</value>
      <webElementGuid>d0e149ee-fe78-47df-a0f8-4cc8084db0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/03 - Attendance/TC_048_RegularizeAttendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>dc9dbb03-0cd6-436f-ac5c-f68e29841a14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outTime']</value>
      <webElementGuid>660d71bc-d917-4498-af3d-f73bb790cdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div[3]/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>4e76071e-c824-462a-8cbb-b25acc20ba5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>23100a28-647b-44db-8cb2-7c4e346bbc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'outTime']</value>
      <webElementGuid>568d6be6-cd2a-476d-b6f4-37921a05826d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
