<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Break Out time</name>
   <tag></tag>
   <elementGuidId>69dce640-178e-4bae-8ed3-370d9e615de1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > input.timeText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2ef674d-9bf0-4eff-bc5a-b8075459d9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>140511ac-3615-4700-a6f4-1969f2868e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timeText</value>
      <webElementGuid>3f7af5da-ac35-4e7b-8b88-60296e1372ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calculateHrs();</value>
      <webElementGuid>a226334b-a89f-45bb-a380-418c98170038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9ae1fe53-256f-432a-965e-de382d2da272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breakTable&quot;)/tbody[1]/tr[1]/td[1]/input[@class=&quot;timeText&quot;]</value>
      <webElementGuid>fb02cb1d-aca6-4107-86de-baf3a5e99d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/03 - Attendance/TC_048_RegularizeAttendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>f67a01e3-fc9d-4c04-a62b-ad9af7b05ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>b60c41d6-05f7-4b0e-99a8-fbc68ec41988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='breakTable']/tbody/tr/td/input</value>
      <webElementGuid>a55d4711-499a-42c3-9ffa-9de19acadcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>d2a78b23-fcfb-4460-9fe3-7af53e4aee9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>13570fbe-8417-4f4a-acd5-475b9e71373f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
