<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_In time_inTime</name>
   <tag></tag>
   <elementGuidId>4840d9e1-b0b7-4bd8-b7fa-47552fac9de1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38eecc32-9dcc-477b-9ebb-2081387698bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control timeText hasDatepicker</value>
      <webElementGuid>f35c9bdd-95d7-4e6d-9800-17eb1bedbcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f70a676a-347c-46d2-bdc3-2a16a2e96319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inTime</value>
      <webElementGuid>be8afcfa-47b6-4b38-8514-035dc2b4edda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calculateHrs(); </value>
      <webElementGuid>6ca366d6-eb5f-4561-a62d-be4ba651d2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>09:00</value>
      <webElementGuid>0ee70a23-75b5-444a-a6ea-0021d1de2f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ce938c06-504d-4daf-9ea6-fe377a278b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inTime&quot;)</value>
      <webElementGuid>aeed5db5-cca5-480c-9314-ef461b29b282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/03 - Attendance/TC_048_RegularizeAttendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>60647e2b-ca52-4eee-8c12-d9abebac16ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inTime']</value>
      <webElementGuid>1fe10c2c-e3d9-47cf-b16c-8a28102b4334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div[3]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>0ae780d6-8ba1-475b-8a16-034f971d8ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>5b9c0c8a-0688-4d7e-8db6-2ece102b1c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inTime']</value>
      <webElementGuid>da4b0e5d-1bb8-43c8-bddd-f2e8d7943e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
