<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_notes</name>
   <tag></tag>
   <elementGuidId>97660acd-c297-43ec-bc4c-53845e939753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#commonNotesData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='commonNotesData']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b15fb437-b044-4b59-9605-8d3c0010f22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control expanding-textarea</value>
      <webElementGuid>d63f57c9-177a-48ef-bc92-31475a3a6207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commonNotesData</value>
      <webElementGuid>fd418df1-b2d9-40af-bc45-68da9f2eb527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commonNotesData</value>
      <webElementGuid>02c4c78d-e891-44fd-8f5d-45b7b8b7b580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write a comment...</value>
      <webElementGuid>0df06d1b-cb48-48dd-9197-caf1551c6e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f254f444-96ba-4835-ae8f-c0a84f7dea2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commonNotesData&quot;)</value>
      <webElementGuid>98496375-6f2a-4b0a-b30e-66c7c671ba23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/03 - Attendance/TC_048_RegularizeAttendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>abfc156d-91ec-4a1b-bac8-1c5712355f3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='commonNotesData']</value>
      <webElementGuid>3dec4ac9-adfd-4cd6-af92-cabdba819cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noteBoxId']/textarea</value>
      <webElementGuid>073e97a9-037b-4ce1-ade2-871810044e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3f1f4d28-1d58-4e49-9637-0f7201da6961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'commonNotesData' and @name = 'commonNotesData' and @placeholder = 'Write a comment...']</value>
      <webElementGuid>8f8ac18e-d8a1-46fa-9b92-01ae80a2448a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
