<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Session has expired. Please log _6da4ef</name>
   <tag></tag>
   <elementGuidId>bd9e7951-e92e-4585-ac49-05a7b7f1f8de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d82fa1b5-4142-4806-b0bf-7d563d96dc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>67374941-b987-4763-9ddb-c6e11ce45803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>7080503f-8682-45df-86ce-2c7734ddb36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7e9d65d6-1b3a-49f9-96ea-e8046c17b4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pId</value>
      <webElementGuid>db11a62e-c3df-4c62-be59-bf69f8ee9700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box lock</value>
      <webElementGuid>e4a797ac-de44-461c-a2c8-03f2f3e2f359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:detect_Key(event);</value>
      <webElementGuid>a5004376-16c6-4b90-8f3a-413314e4009c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>document.logonForm.password.select();</value>
      <webElementGuid>6ede29c4-bc65-4071-bcd8-1d3753a95f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pId&quot;)</value>
      <webElementGuid>91e15691-dc92-4ec9-943a-ab7e959379a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pId']</value>
      <webElementGuid>317b4884-3cd7-4fb0-b52e-1c149d72dbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>c7dcef5e-5c12-4e26-aa97-e966e7923a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @name = 'password' and @id = 'pId']</value>
      <webElementGuid>8816bdcc-e97b-490e-9e93-2fc3d8270563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
