<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Share a suggestion_empxtrack_feedback_subject_by_client</name>
   <tag></tag>
   <elementGuidId>ed036d55-c844-4830-9463-6e154245d7b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_subject_by_client</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f830f4e-98e1-4f0a-bc0b-c29ede4acf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c1235ab-ce82-4990-b1ff-9f947437e0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_subject_by_client</value>
      <webElementGuid>208fd02c-3c13-470b-8e00-46ff8bbe97a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01c12b29-6ea2-434c-902a-124f042e1b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Specify area</value>
      <webElementGuid>4ae4daa7-3e89-4196-9792-a85606bcefbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_subject_by_client&quot;)</value>
      <webElementGuid>d1d5e3f7-75b2-490b-9139-9b65819b379b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      <webElementGuid>01dba1f8-616b-4e5f-867f-1fc5a8d5a6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>a6a664ab-78e4-4c03-b0dd-b2d3562fe7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>163b4333-368e-40f8-8296-c159da464f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'empxtrack_feedback_subject_by_client' and @type = 'text' and @placeholder = 'Specify area']</value>
      <webElementGuid>af428aae-0a77-4bb2-a9c9-8a1c1f54d6e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
