<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Check for anonymous submit_checkAnonymousSubmit</name>
   <tag></tag>
   <elementGuidId>8c7fee27-8593-4df3-b742-f7ad0f9861b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkAnonymousSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkAnonymousSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64456cab-a304-4468-a9d4-8061f919c1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>28a35c4f-cf01-4f5b-99de-b2e5492f5ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkAnonymousSubmit</value>
      <webElementGuid>054b0a9b-af1e-4089-b2e9-90962eed081d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkAnonymousSubmit</value>
      <webElementGuid>c99f6450-410b-43e8-bb7e-9ac56b1d9b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkAnonymousSubmit&quot;)</value>
      <webElementGuid>94d2ef19-5d6c-4cbd-aab6-5dd85118768d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkAnonymousSubmit']</value>
      <webElementGuid>f4a87ac1-5008-49c1-8c5a-42639ba9a176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[3]/label/input</value>
      <webElementGuid>46a26d47-9078-4f45-a4cc-63e9c3ac0bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>b177592c-d709-4867-b901-7e43d89bd3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkAnonymousSubmit' and @id = 'checkAnonymousSubmit']</value>
      <webElementGuid>47ccac56-816a-40bb-84e9-10fa8611778e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
