<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Share a suggestion_empxtrack_feedback_by_client</name>
   <tag></tag>
   <elementGuidId>7622e0a7-a641-437f-bb8a-9a0b63e48e1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_by_client</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='empxtrack_feedback_by_client']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cd469a4a-9028-424f-ae4a-17024f81c8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>64f0fd39-0105-4568-9b9f-65a5f2b558e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_by_client</value>
      <webElementGuid>17e168e9-3132-4f76-ad42-57922d025968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your suggestion</value>
      <webElementGuid>2de1b98c-c13d-4c9b-8bc6-1daa560881ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>533b5fcf-1bb6-4d76-9d5d-8cbb17084ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_by_client&quot;)</value>
      <webElementGuid>341e3f18-e3f7-4fcc-ba7c-129899ce342f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='empxtrack_feedback_by_client']</value>
      <webElementGuid>8bab8f72-07e7-42e6-b516-f328787f300d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>ebeaace3-3d12-411b-8537-7f71f7d565d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a457d3cc-a503-463b-885d-240f74371778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'empxtrack_feedback_by_client' and @placeholder = 'Your suggestion']</value>
      <webElementGuid>a618021e-6ee1-4c9a-b930-a92fe89e546c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
