<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply Button</name>
   <tag></tag>
   <elementGuidId>145b2c67-2d9f-4e84-a9b7-275980721f91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actionItems_renderTableHeaderArray_1706717310964_1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='renderTableHeaderArray']/tbody/tr[2]/td[3]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>042c1304-a2c2-4556-b7ba-25a99db14891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>304878a5-149e-469a-9688-0c3809e93da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>triggerMenuClose('_navBarId_renderTableHeaderArray_1706717310964_1');javascript:addLeaveRecord('4');return false;</value>
      <webElementGuid>46fe1f2b-a238-469d-8bdd-ce044bff84a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionItems_renderTableHeaderArray_1706717310964_1_0</value>
      <webElementGuid>56cde7de-aa2b-4eb8-bdc8-4ade363df30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>d09e6d93-b089-4e3a-97f4-2c869eb784f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Apply</value>
      <webElementGuid>34dee3b0-9b38-4f70-8ec5-89fe25e6efbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionItems_renderTableHeaderArray_1706717310964_1_0&quot;)</value>
      <webElementGuid>5b1b43e5-2fe7-4aed-a4b6-23341e46057e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='actionItems_renderTableHeaderArray_1706717310964_1_0']</value>
      <webElementGuid>037fadc4-6111-45a9-bb0a-fc7561d46868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='renderTableHeaderArray']/tbody/tr[2]/td[3]/div/ul/li/a</value>
      <webElementGuid>eda4a6e8-1bd1-435b-bb4b-b3d635756f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Apply')])[2]</value>
      <webElementGuid>6d2ebb1e-0f3b-4d10-83ea-d6a36a673ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[2]/following::a[1]</value>
      <webElementGuid>23e4ae53-c309-43b3-9c02-c823435544e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Earned Leave'])[1]/following::a[2]</value>
      <webElementGuid>74ddea27-3b87-4a29-83d7-9d6cf7596622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sick Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>52e77c56-5757-404a-8030-83fbab7b4159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::a[1]</value>
      <webElementGuid>77ddb2e9-3490-4b80-9021-561b70041000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[13]</value>
      <webElementGuid>3739dc83-937c-4597-a5da-a9911576fd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/ul/li/a</value>
      <webElementGuid>f629c960-4183-4cff-a42b-fe37cf38ae3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'actionItems_renderTableHeaderArray_1706717310964_1_0' and @title = 'Apply' and (text() = ' Apply' or . = ' Apply')]</value>
      <webElementGuid>3c5dc9e8-5c92-436d-8ffc-901767ccecec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
