<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Half End Date</name>
   <tag></tag>
   <elementGuidId>99f824ca-d7dd-4e0b-b48b-fa84d4d51650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondHalf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondHalf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e445e097-2a55-43f2-a3cd-df849dd36c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.secondHalf</value>
      <webElementGuid>d163ac74-3c99-416c-ad64-a5f8d1b1c1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2363b200-9335-4c38-9e86-cd6e8daa4735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondHalf</value>
      <webElementGuid>8d6471d1-f756-43a5-b81f-545e925810c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>124f2dd1-7f13-4868-ae41-6a748c27bfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:calculateDaysOnCheckBox('');return true;</value>
      <webElementGuid>df51cc95-cead-4888-97b1-eb0b9c5c58ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondHalf&quot;)</value>
      <webElementGuid>87de2814-15cb-48ef-a698-3b00b1ab29db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/03 - Leave/TC_030_EarnedLeaveFail/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>4ce5fc39-3844-40dc-9b49-50799d6d1c27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondHalf']</value>
      <webElementGuid>4800ffe3-b7d7-4de8-8a06-a7217d407245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveDetailSection']/div[2]/label/input</value>
      <webElementGuid>83a4b875-78a2-447d-9fe9-989bf6e6a8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>645cd045-d3d4-420b-a75f-b94c30cc3d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataObject.secondHalf' and @id = 'secondHalf' and @type = 'checkbox']</value>
      <webElementGuid>c519c9d8-c5a0-42a5-aa40-d9af91160499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
