<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Half End Date (1)</name>
   <tag></tag>
   <elementGuidId>04ec2fe1-6497-4645-972f-ed5f415333e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondHalf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondHalf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05556d6f-ed43-4aee-8d2a-696957e668c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.secondHalf</value>
      <webElementGuid>982a32ac-da46-486e-a240-4a9fe0246e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fd5ced4-53f8-484c-840f-d5ab468a81d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondHalf</value>
      <webElementGuid>2f7cf31b-9435-417b-8e3e-a4d91937892c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f8a41c98-5c36-49fb-925d-d32ac8b5cdb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:calculateDaysOnCheckBox('');return true;</value>
      <webElementGuid>dcbd775e-850b-4ac2-be2c-6ceb8ead76c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondHalf&quot;)</value>
      <webElementGuid>ea4700cb-4105-4664-97af-b05b4dfe96eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/03 - Leave/TC_030_EarnedLeaveFail/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>2bf1980d-adaf-480f-af9e-0a8cf8c80405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondHalf']</value>
      <webElementGuid>ef90d711-3311-47de-bd5e-504f4a046ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveDetailSection']/div[2]/label/input</value>
      <webElementGuid>c82746ff-b278-4ef0-9b81-412cfad5e43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>4ad3f8c1-3306-45aa-b905-e5cda66fe822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataObject.secondHalf' and @id = 'secondHalf' and @type = 'checkbox']</value>
      <webElementGuid>49e52234-e09b-4acc-a6d4-002c54bf1871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
