<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobbies_button_Hobbies Ok</name>
   <tag></tag>
   <elementGuidId>10641de5-edbc-49b8-afe2-8abcfac9d1e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0892bc8d-29db-4ed1-bb0c-817118578516</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'btn btn-success' and (text() = 'Ok' or . = 'Ok') and @ref_element = 'Object Repository/TC05 - Self Services/01 - Profile/TC_042_AddProfileDetails/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66180b9b-9c2f-4b3f-9862-cc30ffc425d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>783df404-aa60-438a-bcd9-612b1155fc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0892bc8d-29db-4ed1-bb0c-817118578516</value>
      <webElementGuid>9e94fbfe-4326-4b00-8946-ddece565c610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>ea33daee-2570-4608-acfc-60bc0b0bdbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0892bc8d-29db-4ed1-bb0c-817118578516&quot;)</value>
      <webElementGuid>6768008f-0272-4689-9bdf-c71babcc8d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/01 - Profile/TC_042_AddProfileDetails/Page_Home page/Hobbies/Hobbies_iframe_Self services_homePageFrame</value>
      <webElementGuid>94729c91-c1c2-42f2-b45c-be8825971d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='0892bc8d-29db-4ed1-bb0c-817118578516']</value>
      <webElementGuid>8d7da295-44aa-4018-9dd0-c3320cd4e7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='26c9a612-94db-41d1-b96b-e73701a58b09']/div/div/div[3]/div/div/button</value>
      <webElementGuid>5bb1b947-055f-4cdc-b7b3-9ba4004179be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record has been added successfully.'])[1]/following::button[1]</value>
      <webElementGuid>1e691ea5-6685-410d-b4ad-98c356ac98b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>6c4680b7-f8c4-4929-9822-b2bf17fec0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>53de87b8-ef08-466a-a8f1-2ef735bdad6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>339d012a-8073-4df1-8458-d2a74961c82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '0892bc8d-29db-4ed1-bb0c-817118578516' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>536037f6-97c2-4de0-9e66-b8efa6e4c93a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
