<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hobbies_a_Open Hobbies</name>
   <tag></tag>
   <elementGuidId>1bfd2daa-c6a2-43b9-8f1f-93afd32889da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>541a691c-50ec-48aa-8971-673d266e7d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_3</value>
      <webElementGuid>c1a7d362-8a12-4c6d-b4de-fe82b01558da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:triggerPersonalDataModes('AddButtonEmpHobbiesInterestsMethod');return false;</value>
      <webElementGuid>f2d7a3e3-f6e4-4588-90ad-70c24126b09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hobbies </value>
      <webElementGuid>35c18837-af76-4efb-92ca-ecfe8ef81db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_3&quot;)</value>
      <webElementGuid>6acce0d8-4a5e-450b-acb0-6fdbb0506a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/01 - Profile/TC_042_AddProfileDetails/Page_Home page/Hobbies/Hobbies_iframe_Self services_homePageFrame</value>
      <webElementGuid>6a96932f-9671-4007-8e61-a61bdabeb48b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_3']</value>
      <webElementGuid>8cf6b929-e770-4f50-a2e7-cadc2398579f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalDetailsDiv']/div/div/div/div[3]/div[4]/a</value>
      <webElementGuid>fd68b4a6-cbc9-42f1-8d67-b8d4c3649c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hobbies')]</value>
      <webElementGuid>14251a06-5f9a-4d2d-a90f-fee9afc8d967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other details'])[1]/following::a[1]</value>
      <webElementGuid>6a497bb0-0fcc-4c28-bdbf-fe9f4867d041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiaries'])[2]/following::a[2]</value>
      <webElementGuid>b9557aa7-386a-44d5-8bee-f6fe33819b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages known'])[2]/preceding::a[1]</value>
      <webElementGuid>fbcf4f99-b683-45c4-9503-703b7ecc75dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact details'])[3]/preceding::a[2]</value>
      <webElementGuid>48f7a559-1fe5-4eeb-8197-e7fa00c28325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>7e2bd8dc-a0bf-4785-9a13-960ae1896769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_3' and (text() = 'Hobbies ' or . = 'Hobbies ')]</value>
      <webElementGuid>8675b0fb-13ae-47fd-99e3-21b04b0d2b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
