<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Update</name>
   <tag></tag>
   <elementGuidId>15fe5b2e-4e8c-42ff-bc2e-0cdfc38ed15c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Update</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Update']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8fef2ee-e9ba-4e7e-8f9b-bafd673667d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_primary </value>
      <webElementGuid>d556b5d5-50da-4b46-a878-10195b31a164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Update</value>
      <webElementGuid>a6df43cc-9087-46c1-bb03-fca4997720f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:updateEmpPasswordInfo();return false;</value>
      <webElementGuid>777f5c9d-765b-4463-bb16-7f16bba19d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>11ac5967-9279-4958-8193-cc549104c8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Update&quot;)</value>
      <webElementGuid>992f743e-b6fb-427a-8cbc-1c92b0126f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC07 - User Profile Icon/TC_067_UpdatePassword/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>057bf7e3-01ea-4fc7-ac8d-dc6990036b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Update']</value>
      <webElementGuid>16474c70-432c-4f1e-8a27-6b7fdad73e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section-panel']/div/div/div[3]/div/div[2]/ul/li/a</value>
      <webElementGuid>e3447aae-88a0-4aca-b63d-c092978acdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Update')]</value>
      <webElementGuid>25b0ac71-b791-436e-8c1f-e9c01fa218ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixture of alphabets(A-Za-z) and numeric (0-9) characters'])[1]/following::a[1]</value>
      <webElementGuid>342b778c-c154-4cb0-8071-96cc80ca048d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[1]</value>
      <webElementGuid>e1970cf8-c8d5-434d-a6b2-fccbfe7abec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btn_Update', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>aab1c124-775a-4a7a-8dc7-59ad419f4de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>8dba8b11-1f53-4732-a929-64c565c7d6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>94b0ae8b-b89f-4b8b-b0f3-d982015d8b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Update' and (text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>1ffb863e-6b03-4fd1-ac81-f7a9dd357381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
