<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame</name>
   <tag></tag>
   <elementGuidId>42712d90-3702-41ff-8c11-a73db2029cd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>91248a3b-6829-46cd-a631-a531eeba51ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=pf4hxZ2pCGLYJLa%2FgbgK1WOjXNGnrGJ1OkkHwm%2F8nVXPQ1PYlCCfZsgF8nhLKhNkDv5FwMjY1+Ad4ftQLQn05QvcU%2FLxBCzw&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>ad0dae0b-4262-47a8-b382-980ee398a656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>22c066d7-0e45-470d-9d28-2691830cea60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>32f2c0c0-4bc2-4361-8659-ab239f7b5236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>1be07076-368a-4275-8930-5074f59de9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b32e9f47-69fa-4f6c-a8c6-84439136d724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>21d63f0f-780d-4b69-a564-e6cb9300276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>cd6f8645-ee99-41a4-b12d-a874d2900a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>955202ae-0782-48e8-ac96-b441341ad29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>7b86d9a2-a335-4e72-9796-72b19c4ec0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>6231a5d7-0176-483b-8a1a-780f1873ba77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=pf4hxZ2pCGLYJLa%2FgbgK1WOjXNGnrGJ1OkkHwm%2F8nVXPQ1PYlCCfZsgF8nhLKhNkDv5FwMjY1+Ad4ftQLQn05QvcU%2FLxBCzw&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>72adc3c0-140c-4d8b-8c9b-830a53106a96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
