<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame (1)</name>
   <tag></tag>
   <elementGuidId>c98bf9cb-a387-48d0-a24d-e78ff90d6c5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>61ef791c-06cf-4672-a064-23b756e5b444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=pf4hxZ2pCGLYJLa%2FgbgK1WOjXNGnrGJ1OkkHwm%2F8nVXPQ1PYlCCfZsgF8nhLKhNkDv5FwMjY1+Ad4ftQLQn05QvcU%2FLxBCzw&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>5384015b-c577-4631-82fc-f06ffcaf28d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>fa1a9ddb-fea0-4493-9e84-2b0d32c8b408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>7ed67522-a082-4471-bcb5-3bcd5427611c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>18c8ba04-a836-42d3-b878-af8df3ba133a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>4eef940e-c88a-4b70-96c1-6894a108f972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>7b81438f-faba-4c7f-8a68-b01a10d2e6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>87c435b9-95a5-435c-a9de-f1e220b21448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>f02ff130-7e9d-4786-91e7-46941eabbdc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>163fe55f-1b55-4a76-a8d0-bb83c0851d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>33a6b334-7286-491c-8f1c-8467704f2e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=pf4hxZ2pCGLYJLa%2FgbgK1WOjXNGnrGJ1OkkHwm%2F8nVXPQ1PYlCCfZsgF8nhLKhNkDv5FwMjY1+Ad4ftQLQn05QvcU%2FLxBCzw&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>40d73a10-a818-4c18-a2ab-5b6a52c33398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
