<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Old password_oldPassword</name>
   <tag></tag>
   <elementGuidId>9101c419-c340-42cf-9749-f9db955df516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oldPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='displayPageContent']/div[5]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5de5a99d-1cf4-4ec9-861d-bf2640067f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f040bdde-db94-4258-827d-9e37b34cdc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldPassword</value>
      <webElementGuid>4d685ef9-7f88-47f1-bbe9-f6cd46003d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d1b17ed3-7f16-4498-aea7-a5a5603905de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldPassword&quot;)</value>
      <webElementGuid>3bfa2a39-6147-4e64-934d-5e4ee7ad8faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC07 - User Profile Icon/TC_067_UpdatePassword/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>625bce35-886a-4866-95a0-5413af975418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldPassword']</value>
      <webElementGuid>1fd07864-a2bd-442a-a800-73f26ff75ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div[5]/div/div/input</value>
      <webElementGuid>ea6bf9cf-c47a-4f5c-b0bb-9eab39c35582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>05f554d8-fb97-4ff5-af4f-8b89a0fafbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'oldPassword']</value>
      <webElementGuid>5c35b12f-5cdb-49c9-b3d0-f71c25adba4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
