<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_cpassword</name>
   <tag></tag>
   <elementGuidId>5f36dd89-febd-4c9c-a314-8dca83cbd2b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40a45a34-ab8b-4d16-be5a-957f6cd1596e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fb716b96-101a-4c96-ab34-0568181dfd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpassword</value>
      <webElementGuid>fc48f6fd-1aa7-48eb-ad00-1383ed0611bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>471652c1-d432-40a5-a62b-0f3780334930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpassword&quot;)</value>
      <webElementGuid>05fbbcf6-8832-4d67-af96-e3d2ee0415b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC07 - User Profile Icon/TC_067_UpdatePassword/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>8ced7079-610c-483a-b2c4-c3834d0ddf8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpassword']</value>
      <webElementGuid>8f52f54f-3122-4558-bd66-c4003534b80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div[5]/div[3]/div/input</value>
      <webElementGuid>ff06e1ca-0f2d-4386-bbeb-3a107dffa0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>697cb6e3-d6af-4735-b8fc-3fd6f3f2e93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'cpassword']</value>
      <webElementGuid>5a21ba90-9d64-48f2-a3aa-bd4360aaa0eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
