<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_011_Edit Currency</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>70b6668e-9dc8-473a-96fd-697575665ab9</testSuiteGuid>
   <testCaseLink>
      <guid>1e8eb3e9-8b70-4aa1-a4b5-ccf0041e46d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05 - Pay Grades/04 - Edit Currency/01 - Positive/TC_031_EditMinSalary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92ba1a5a-7019-49b5-be98-594dce4569c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28a3a1f0-fea0-49ac-8d90-289b7ad5a30f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad18b864-97eb-4cd4-bd23-d088a14d0535</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89ace8ac-5e55-4a83-92a9-22b401442d5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05 - Pay Grades/04 - Edit Currency/01 - Positive/TC_032_EditMaxSalary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92ba1a5a-7019-49b5-be98-594dce4569c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28a3a1f0-fea0-49ac-8d90-289b7ad5a30f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61c7e3eb-9d74-47ba-9f20-d12f23d7a414</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c166199a-72c9-4cae-83ef-8971a081c1d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05 - Pay Grades/04 - Edit Currency/02 - Negative/TC_033_MinSMoreThanMaxS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>478bda69-e27e-49ac-ac9d-9712eeb6a107</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd3f8d4f-492f-40e2-a80b-7b1dd2b0bf32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad18b864-97eb-4cd4-bd23-d088a14d0535</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61c7e3eb-9d74-47ba-9f20-d12f23d7a414</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
