<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply Casual Leave</name>
   <tag></tag>
   <elementGuidId>0f3ad6a0-8b63-416b-8626-c059b5a01acc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actionItems_renderTableHeaderArray_1706717310959_0_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='renderTableHeaderArray']/tbody/tr/td[3]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98fb835b-b09d-4225-a296-1517a11a62f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>69819c5a-62dd-4675-93cf-dc8296957ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>triggerMenuClose('_navBarId_renderTableHeaderArray_1706717310959_0');javascript:addLeaveRecord('1');return false;</value>
      <webElementGuid>7400e11f-702b-4731-93ef-1c345c7b30e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionItems_renderTableHeaderArray_1706717310959_0_0</value>
      <webElementGuid>e1377991-bf81-4687-b046-1a4d0dec579a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>d3867b2e-8c96-45f9-bcdf-1789f8a81b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Apply</value>
      <webElementGuid>5ef0e7f2-25ae-44d0-81e2-74e6f53d57de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionItems_renderTableHeaderArray_1706717310959_0_0&quot;)</value>
      <webElementGuid>b5404178-b69b-404e-90bf-4eb92109ed01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/03 - Leave/TC_026_ApplyCasualLeave/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>13b34a7f-6c29-4c67-ac52-663d3a9af1c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='actionItems_renderTableHeaderArray_1706717310959_0_0']</value>
      <webElementGuid>6ab08fa0-5da6-4720-8780-066aa2c0e4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='renderTableHeaderArray']/tbody/tr/td[3]/div/ul/li/a</value>
      <webElementGuid>c4a3f96d-989b-45a4-b41b-3e5af1cd123a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apply')]</value>
      <webElementGuid>73ab8bc5-5532-441a-9370-72935f361ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[1]/following::a[1]</value>
      <webElementGuid>7dcd4763-145e-409c-b06a-b32283772222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casual Leave'])[1]/following::a[2]</value>
      <webElementGuid>c567aed6-6c3a-4792-85ab-0150e38d7543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Earned Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>c6f2cf21-55ef-4a86-8497-f02cd4187489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[2]/preceding::a[1]</value>
      <webElementGuid>8f004d71-31eb-4634-b1b8-b55a528a0b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>45973a45-196b-4edd-9c80-571483749896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[12]</value>
      <webElementGuid>889ea7e2-e996-4d66-aeb6-e2030c626a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>ecd95b04-9ca2-4c78-88a4-fc6c17bf16a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'actionItems_renderTableHeaderArray_1706717310959_0_0' and @title = 'Apply' and (text() = ' Apply' or . = ' Apply')]</value>
      <webElementGuid>4d6706c0-5ba1-41af-b320-f84ebac284a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
