<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do not add task on my calendar_addTaskToMe</name>
   <tag></tag>
   <elementGuidId>e47a486c-9686-4e30-8d00-68e070b31286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addTaskToMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addTaskToMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>708ddfd0-968a-45ae-b192-4cc5becbb9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dc118698-d7f2-40d5-bcd9-f78f5fc0da8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addTaskToMe</value>
      <webElementGuid>5f1b1648-39d2-4d9e-8546-8f08c9075885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTaskToMe&quot;)</value>
      <webElementGuid>650439ce-fe46-4155-898d-38c63550b342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/TC_015_AddNewTask/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>05f6e867-3922-42e2-9c6a-f170de8bac03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addTaskToMe']</value>
      <webElementGuid>5e1c0147-0e58-46f2-9d94-180c81d793d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Attendees']/div/label/input</value>
      <webElementGuid>048cc88c-7ad9-496c-a608-27308dfafcb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label/input</value>
      <webElementGuid>89b6d53e-919c-4de5-a160-fc95b6ba277d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'addTaskToMe']</value>
      <webElementGuid>17b644db-376d-4dc9-9643-a8490990459d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
