<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add task for others_addTaskToOthers</name>
   <tag></tag>
   <elementGuidId>2e6d711d-5313-4001-a219-73d60342e8c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addTaskToOthers</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addTaskToOthers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>681ca039-c8ed-4b51-9ce8-00307feb7dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fb968cf7-e81e-405d-af6e-038df7815bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addTaskToOthers</value>
      <webElementGuid>f81b2b05-eb37-44a9-b32f-f91f62fc90f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>disableAttendess(this);</value>
      <webElementGuid>a9609f1b-062f-4f01-b174-4b30495bf9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTaskToOthers&quot;)</value>
      <webElementGuid>7d8935ef-3a9f-40f1-ae2a-7296372a0559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/TC_015_AddNewTask/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>a5441b47-f6ef-4a5e-a5a4-94cc8c4ef235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addTaskToOthers']</value>
      <webElementGuid>721ce29c-cfd1-41c7-a28b-0d21de4b94a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[4]/label/input</value>
      <webElementGuid>fae25cf3-0f04-43b8-91e6-88151d029679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/input</value>
      <webElementGuid>01534ab7-e538-4a75-930c-a5b178afdac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'addTaskToOthers']</value>
      <webElementGuid>147bffb9-fcd9-40f8-92ec-3e4ab523a172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
