<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Due on_date_selectedEndDate</name>
   <tag></tag>
   <elementGuidId>8c5da6e1-2f9f-4c44-92be-331d8a5aab62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedEndDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedEndDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dec2d0af-3c33-4ed7-86cf-25ffd21d8db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92c35603-54fa-4000-b796-e304744d1b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedEndDate</value>
      <webElementGuid>698d2d84-d8f8-4963-8e4e-a16781e58ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_selectedEndDate</value>
      <webElementGuid>605cba12-727f-4429-9365-e02e44f91f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>24140aee-00f9-4f93-9591-9852614190a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedEndDate&quot;)</value>
      <webElementGuid>b65c6473-1783-4caf-ba20-06685a5684bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/01 - Event/TC_015_AddNewTask/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>13e6a08b-0ee4-48be-b6a3-72c4ac2c3602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedEndDate']</value>
      <webElementGuid>2b7cfbf5-4129-4c0a-87a1-cbb91d97b81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[2]/div/div/input</value>
      <webElementGuid>7e4df26a-285d-4976-a8a5-337fd10bc424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>9558f11b-8c96-48d2-8a37-0020b80d3480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectedEndDate' and @name = 'date_selectedEndDate']</value>
      <webElementGuid>e487a4be-5db4-4e82-8b0a-aa6e7af83c17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
