<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My tickets</name>
   <tag></tag>
   <elementGuidId>91493abb-ab43-4fa9-bcac-84994059b168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_manageHelpDesk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='My tickets']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44b28c7b-fe69-480c-a670-7c4baba903cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>15b4627b-f9c1-4467-ab04-49276c4b33c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_manageHelpDesk</value>
      <webElementGuid>a1a64902-51c8-40c6-8dbe-f993d7a4957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('runet.do?activity=submit&amp;mod=MyTicketHelpDesk')</value>
      <webElementGuid>e2fa2620-e59d-4206-9673-7482c86670df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>7a5f1c7b-2725-4e63-9068-0a6fd21421fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My tickets</value>
      <webElementGuid>64334af8-908b-428d-8276-fe11f436d030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_manageHelpDesk&quot;)</value>
      <webElementGuid>0de7d331-402f-448d-b8df-73dcec73b6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/04 - Tickets/TC_051_ViewMyTicket/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>e4be6d20-7909-45f8-b9a0-ed74a955c2be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_manageHelpDesk']</value>
      <webElementGuid>0b54d91c-3154-4be3-a74c-98731a2d6f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showMyTicketsHelpDesk_getSecondaryLinks']/div[2]/a</value>
      <webElementGuid>d39a3c61-ecd5-42ce-8466-93428f6547f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My tickets')]</value>
      <webElementGuid>e00ab713-8a68-461b-b465-0941d65b6cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[1]/following::a[1]</value>
      <webElementGuid>9ba2cc39-c35b-459d-a0c6-339b4af393d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[2]/following::a[1]</value>
      <webElementGuid>df707078-de32-4f26-b9d7-16f295657d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create ticket'])[1]/preceding::a[1]</value>
      <webElementGuid>8e0f7f92-fae7-4266-a659-fb9a575d888b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver: 10.10.04'])[1]/preceding::a[3]</value>
      <webElementGuid>e825611b-0fd1-459f-a33e-9abe4bd66616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My tickets']/parent::*</value>
      <webElementGuid>38d0e69f-e5ff-4584-a517-677de8c61fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[10]</value>
      <webElementGuid>bba29769-2e54-495f-9bd6-c37ff51a0d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[4]/div[2]/a</value>
      <webElementGuid>2f7469a1-91dc-4e1b-b7ca-7004c613e54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_manageHelpDesk' and (text() = 'My tickets' or . = 'My tickets')]</value>
      <webElementGuid>f11b9001-7f17-4e59-b64e-441abd25a5a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
