<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Help deskTickets</name>
   <tag></tag>
   <elementGuidId>0a2b2995-f814-44bb-86ec-f0970bb718d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showMyTicketsHelpDesk_headerV10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Help desk/Tickets']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>090251cb-5a3f-46fa-8fad-b129ea247126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showMyTicketsHelpDesk_headerV10</value>
      <webElementGuid>3c089f15-c42b-4404-88b0-f7767b76d2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10widget-tite-font</value>
      <webElementGuid>803d72fc-b3ec-42bb-933f-47745e3460ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Help desk/Tickets</value>
      <webElementGuid>112eda72-9c2a-4bb3-a3fa-f71b8eb54dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showMyTicketsHelpDesk_headerV10&quot;)</value>
      <webElementGuid>d10b47ea-89a0-4cf2-937f-a0c14e637a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/04 - Tickets/TC_051_ViewMyTicket/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>cfbe5f68-9374-4e27-a3dc-48bc89e3a746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='showMyTicketsHelpDesk_headerV10']</value>
      <webElementGuid>d0d535dc-8ed4-448b-87a6-763eea7ccb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='head-areaV10']/h2)[4]</value>
      <webElementGuid>d251b384-48ed-43c7-88de-1290f6d0d0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data not available'])[1]/following::h2[1]</value>
      <webElementGuid>cef8bf41-73ff-4ae3-a175-27179199ca44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket id'])[1]/preceding::h2[1]</value>
      <webElementGuid>1dd68bbb-3517-460e-a01b-7214a6a657fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Type'])[1]/preceding::h2[1]</value>
      <webElementGuid>ed3f33f5-7e91-44b6-807c-2067c7910e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help desk/Tickets']/parent::*</value>
      <webElementGuid>ca8fd5a4-dac3-4752-9ebf-0a8e764bb8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/h2</value>
      <webElementGuid>d2d1753f-10b1-40ef-8783-4c4887ecb73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'showMyTicketsHelpDesk_headerV10' and (text() = ' Help desk/Tickets' or . = ' Help desk/Tickets')]</value>
      <webElementGuid>50b9e047-dea0-4f2c-a299-740c97bf196a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
