<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Profile Icon</name>
   <tag></tag>
   <elementGuidId>3d807a7b-9ac8-46e8-91aa-eff0cdcd8e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.empInitial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profileImage']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f39907a-9a44-413f-9e31-6eb0cea009e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>empInitial</value>
      <webElementGuid>2830d5aa-ccbe-4161-b682-9969b08d8b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>e</value>
      <webElementGuid>cab50efb-5bed-4ecf-a5b3-8bb6bcfa31b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileImage&quot;)/div[@class=&quot;empInitial&quot;]</value>
      <webElementGuid>672ecb8e-80d6-4a06-8912-262389231027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profileImage']/div</value>
      <webElementGuid>b3f2ebed-177e-45fe-a599-51c0bd1a8bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/following::div[4]</value>
      <webElementGuid>f3c7a033-3331-43ad-8623-0e9720f18627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 01'])[1]/following::div[5]</value>
      <webElementGuid>53a0c240-0992-4851-a5ee-0718a3487c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 01'])[2]/preceding::div[3]</value>
      <webElementGuid>7940df88-bef8-40e1-a2fb-755a598ca38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default | Default'])[1]/preceding::div[5]</value>
      <webElementGuid>8bfc6fbb-6b43-4f27-aee0-a058ac822bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='e']/parent::*</value>
      <webElementGuid>daa967af-8bdd-440c-b894-631ec9b19b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div</value>
      <webElementGuid>fe86f08c-15d9-4bc2-8ef7-5224f65251dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'e' or . = 'e')]</value>
      <webElementGuid>e528cd83-05c6-47e5-a41d-69e9bb5d1a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
