<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Bar</name>
   <tag></tag>
   <elementGuidId>4721e0cc-94f9-401d-b83a-1f9bbfe6222b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_selectedSearchOnTicketId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_selectedSearchOnTicketId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79695f78-30f4-4f9d-9faa-be1f4ab501f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_selectedSearchOnTicketId</value>
      <webElementGuid>76ae2019-7a55-4e4e-a036-cf1e8b670906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0a31f5d7-c13d-46aa-b3a8-d840d21e24a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9f02784-3089-44e9-a040-55b52efd519f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search on ticket id</value>
      <webElementGuid>e3031d37-5c1f-4741-93e4-16837fce9da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c38f5862-ae48-4c76-bc70-fa885be861c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_selectedSearchOnTicketId&quot;)</value>
      <webElementGuid>796ed588-eae9-457f-9b3b-c594d6d97245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/04 - Tickets/TC_055_SearchTicketID/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>dbf3fb84-3ef4-4621-bba8-375e543f7854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_selectedSearchOnTicketId']</value>
      <webElementGuid>b62d082a-62aa-42fb-8f83-7935cb37ceea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_filtersOnTicket']/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>9e28643e-fbed-4025-8b95-7657c51d38ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>848c55d0-f3de-41e3-b4a4-2e470f5665b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_selectedSearchOnTicketId' and @type = 'text' and @placeholder = 'Search on ticket id']</value>
      <webElementGuid>6f11d469-9e89-4796-8825-0c11a29a992e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
