<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Attendance</name>
   <tag></tag>
   <elementGuidId>418317d0-1a75-4f1c-8c86-d8fa7a94ef73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#heading_page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='heading_page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c3810641-53f7-4906-bf92-6d0c60f57fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>heading_page</value>
      <webElementGuid>d528ec8c-843a-41d9-a5f5-5b265fc0b47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading_page</value>
      <webElementGuid>b08bfe9b-ae24-416c-820e-4c400b0df4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attendance</value>
      <webElementGuid>f51c3221-5d03-40bb-a489-f1bcfcf605ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading_page&quot;)</value>
      <webElementGuid>2020a689-32c1-4df6-9296-6d9643cba628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/03 - Attendance/TC_050_ViewDashboardFullPage/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>4e7eb91d-2f51-4196-b259-fe7b75b655b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='heading_page']</value>
      <webElementGuid>df8f4f4b-8ecf-40c6-8648-1c32a65f6971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div/h2</value>
      <webElementGuid>f4694533-5182-4485-b8ed-e6d3a1303b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::h2[1]</value>
      <webElementGuid>8c5a97e8-4987-415a-969a-312dfc5acdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attendance']/parent::*</value>
      <webElementGuid>5293f65a-a945-4bea-b6fd-9e20ec53d517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>c93571da-96df-491e-bf7c-4068b79ad698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'heading_page' and (text() = 'Attendance' or . = 'Attendance')]</value>
      <webElementGuid>456f1aa8-bf74-4dcf-b28a-5f1c1562d896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
