<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave transactions</name>
   <tag></tag>
   <elementGuidId>731a5235-4425-47ba-ac2f-e8c61a0b7c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_showMyLeaveTransaction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_showMyLeaveTransaction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0283cb3b-7db0-4c31-bc52-237086321ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e885a75a-0303-43a1-a831-2d14e4d519a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_showMyLeaveTransaction</value>
      <webElementGuid>b854f622-cd24-4f51-88c7-15f04822191f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('mod=MyLeaveDetails&amp;secondaryVar=extendedDwrMode^showMyLeaveTransaction')</value>
      <webElementGuid>af175c76-0e1a-4653-a441-4a5c83646520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>02b6e3ea-bb70-4860-b891-88137f67377b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave transactions</value>
      <webElementGuid>37b8699c-5340-4269-a481-5069e829a2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_showMyLeaveTransaction&quot;)</value>
      <webElementGuid>75947025-bf61-48e0-b6d7-a527f9111b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/02 - Leave/TC_047_ViewLeavePolicy/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>9aec9a07-e1ba-4a7d-a393-9f88c9e439b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_showMyLeaveTransaction']</value>
      <webElementGuid>4b2766a6-f0c6-4ee3-bb3f-324514d4f8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveGroup_getSecondaryLinks']/div[2]/a</value>
      <webElementGuid>51ad5c8d-6f93-4581-81a3-24359901e108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leave transactions')]</value>
      <webElementGuid>81a54ed5-d2e1-46ac-9774-8add0ff1639c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::a[1]</value>
      <webElementGuid>83e064f2-cfeb-4bdc-b4f4-aae101ddee8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[4]/following::a[2]</value>
      <webElementGuid>310d62aa-2d9e-4950-adfc-75b5c1abb89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Calendar'])[1]/preceding::a[1]</value>
      <webElementGuid>72145649-d909-4ab2-bfe3-52d832f07151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Leave Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>50127fcf-eca1-468a-bff5-08ed763ba307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave transactions']/parent::*</value>
      <webElementGuid>67c07e84-3ace-45de-affd-29c6f88a2dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[6]</value>
      <webElementGuid>722b68ca-fc86-4fb9-91f2-38833b5fa10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[4]/div[2]/a</value>
      <webElementGuid>eab03a76-2415-4636-8f10-416dd11091d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_showMyLeaveTransaction' and (text() = 'Leave transactions' or . = 'Leave transactions')]</value>
      <webElementGuid>1591c016-2147-4e36-8d35-a413eeed0d5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
