<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Self services_homePageFrame</name>
   <tag></tag>
   <elementGuidId>188f950c-ef4b-44c3-bc10-f71d343878df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>09983704-64a1-46d6-8f0c-d5f9c7c5314e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=GWVNfPq8cZnGsvK1Xva4Qz3FUSq3A%2FGxyzi2i%2FBaiBdUFDXpThWC3B+7y60b6oPaWcSp2oTaYHQBxgyd37SJew%3D%3D</value>
      <webElementGuid>c0452b60-3b6e-43ce-8cc1-db309f68e798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>08c47d7a-caea-4d1f-8c03-3c6d19f6593e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>e67cde86-1f99-4676-ad30-f5700a19f913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>bc7f93c9-b788-49c7-ad70-ebd4f8db7023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>8365dd28-0b70-4c39-9a02-590b65b537cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>756d0c02-4c28-46e7-bee7-1eb708a6ea66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>18633de6-550f-40c7-878e-af5fd128f466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>86e812c9-e643-4f58-b543-43516a4dde92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=GWVNfPq8cZnGsvK1Xva4Qz3FUSq3A%2FGxyzi2i%2FBaiBdUFDXpThWC3B+7y60b6oPaWcSp2oTaYHQBxgyd37SJew%3D%3D' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>dc7787a8-ace4-4740-9a3d-9a6400cca63a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
