<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expected date_date_expectedDate</name>
   <tag></tag>
   <elementGuidId>5d496b0c-2d02-49a7-aa8a-897628cc800a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expectedDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expectedDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdee3884-2bef-44fe-aa2f-6afc9ec0474f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df62dbee-488e-40e2-b427-d5144edb9dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>873a2812-2677-48a8-8a3e-fea219eae401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expectedDate</value>
      <webElementGuid>68b988b5-20df-4542-8d06-21df68b39479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_expectedDate</value>
      <webElementGuid>a79b555c-20bb-46ee-9fef-b37293aaeeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expectedDate&quot;)</value>
      <webElementGuid>51b4cfa0-5a1e-4ab9-812d-daf4a7408864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/04 - Tickets/TC_053_CreateTicket/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>3ed6da47-b4c9-483e-8f94-e69a9abcfb45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expectedDate']</value>
      <webElementGuid>3dff8e28-bf16-4dfc-a6b8-76d677161ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-wrapper']/div[4]/div/input</value>
      <webElementGuid>505e480d-f774-4b0d-bed0-82c1212dc808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>899ba7e9-29df-477c-a62d-df3b7cf2113c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'expectedDate' and @name = 'date_expectedDate']</value>
      <webElementGuid>b6c52a64-904f-4b72-9526-edc53e769410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
