<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select to open Drop down</name>
   <tag></tag>
   <elementGuidId>e19c9424-796b-450f-8fa0-58587dc520a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ticketType_chosen > a.chosen-single > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ticketType_chosen']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>458eac1e-d107-4d23-80f8-017bbb3a02fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---</value>
      <webElementGuid>b2e5cd7e-fb7b-4815-bc98-e46ff309b959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ticketType_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/span[1]</value>
      <webElementGuid>980fcd45-3cf3-4223-9b31-728c38fc60d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/04 - Tickets/TC_053_CreateTicket/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>f357fd2a-f835-4400-8c33-a560ee0ba1ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ticketType_chosen']/a/span</value>
      <webElementGuid>9a2ed4aa-9076-4af5-9850-db38bede7060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Type:'])[1]/following::span[1]</value>
      <webElementGuid>f2dc0223-a396-472c-ad34-1b8f5c091add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::span[1]</value>
      <webElementGuid>4a1335fb-33fa-4aba-836c-0b68bf26424b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='---Select---'])[3]/preceding::span[1]</value>
      <webElementGuid>2846dca3-57f1-488c-80a6-136848bb506c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resource Request'])[3]/preceding::span[1]</value>
      <webElementGuid>22d081c4-d380-462f-a21a-485bb3c60b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/a/span</value>
      <webElementGuid>d03b187d-e344-49d5-851e-e0b091b68da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '---Select---' or . = '---Select---')]</value>
      <webElementGuid>9880875a-c3e4-4f31-910d-947ec26d66fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
