<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  10</name>
   <tag></tag>
   <elementGuidId>35433763-27da-4766-ae5d-7182222c542f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f613e19a-65df-4c3b-a1ef-39c9cd758cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank</value>
      <webElementGuid>e09696e2-293c-4547-ab57-fa415457606f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>786777ca-4919-4510-bd0d-55da9ff18ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  10 </value>
      <webElementGuid>1df2f117-1a49-4a44-83f9-3c763c800f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank&quot;)</value>
      <webElementGuid>b2e98ebc-dc48-4df7-8551-47bb59222572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank']</value>
      <webElementGuid>4c588733-a103-43d2-b56e-24ff623ec929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[10]</value>
      <webElementGuid>331e1d5b-d8d1-4f34-8cbd-09e3c1bb31c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>072ebcd1-9a4c-4ade-8e19-552648ef9ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[1]</value>
      <webElementGuid>17f95994-aa23-4df1-8673-d667c2652f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]</value>
      <webElementGuid>95123ff7-da28-4c95-ba2a-49f9269940cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank' and (text() = 'View details for: emp  10 ' or . = 'View details for: emp  10 ')]</value>
      <webElementGuid>631d1fab-4b28-4b8c-994e-b98f47c023f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
