<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  02</name>
   <tag></tag>
   <elementGuidId>79c0e7e3-3edb-4beb-bf27-468cb16f9653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ajax_listOfOptions']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0fee41b6-3939-4314-b187-33ca93668b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank</value>
      <webElementGuid>bd4a9d3f-5ec9-4184-bbbb-d77de42bc174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>4fbe6f0c-a189-4cb0-b8f1-41d2759dd4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  02 </value>
      <webElementGuid>26ac9230-1c0b-405b-871f-3120089d9a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank&quot;)</value>
      <webElementGuid>f2df94fd-f1e1-45b5-af78-96ceffcd33b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank']</value>
      <webElementGuid>13777661-1289-4b5f-934d-4e72ecec2485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[2]</value>
      <webElementGuid>c0bb8a8c-1078-4f34-b682-06274855b647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/following::div[3]</value>
      <webElementGuid>6a80d483-a32b-47b4-a2db-d83c0c74e237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]</value>
      <webElementGuid>2e9b3ec1-457b-4b51-bb3f-d999dabfcc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank' and (text() = 'View details for: emp  02 ' or . = 'View details for: emp  02 ')]</value>
      <webElementGuid>ddf0eb46-7689-4de0-85c5-9adff3fafc8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
