<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  04</name>
   <tag></tag>
   <elementGuidId>2cf6a938-8a8a-46a7-87a8-6e3bb018abb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c93ef18-5d02-40a5-a838-2424d3df1c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank</value>
      <webElementGuid>4961ce60-468e-43c4-aa36-635cea9077c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>5a5aef1c-3a8c-42fd-af51-ea5a2ff9f42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  04 </value>
      <webElementGuid>574c1a54-dbff-4923-ace0-e68bb29d0822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank&quot;)</value>
      <webElementGuid>60ffb67c-0bb6-44d6-8eea-1e61ef10cd38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank']</value>
      <webElementGuid>5af2b855-faa6-4738-a41c-980339e05d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[4]</value>
      <webElementGuid>81ca01ac-0ffb-403c-9a76-c8ed35b8d45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]</value>
      <webElementGuid>66cc32d7-fa0b-44ec-8368-75edfe7f46ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank' and (text() = 'View details for: emp  04 ' or . = 'View details for: emp  04 ')]</value>
      <webElementGuid>dbb6aa64-43e2-4aa6-b06d-260a347569c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
