<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  03</name>
   <tag></tag>
   <elementGuidId>baa063b7-695e-4278-81a9-22bf9808e538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhG2sefNnOcLL33JnqGX4w4FSucEcm60J4xxHbTMb9HbvhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOv7Ib+sDdhHE$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6af90486-507a-4161-9ba3-21dea0aa41d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhG2sefNnOcLL33JnqGX4w4FSucEcm60J4xxHbTMb9HbvhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOv7Ib+sDdhHE$$panel$$_blank</value>
      <webElementGuid>ffca4181-8c9e-4ff5-880f-59ad81705324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>0deff082-15f3-41bd-998e-994611975383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  03 </value>
      <webElementGuid>7efd0d6f-70e7-4c0f-8f1b-bb1ec8401c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhG2sefNnOcLL33JnqGX4w4FSucEcm60J4xxHbTMb9HbvhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOv7Ib+sDdhHE$$panel$$_blank&quot;)</value>
      <webElementGuid>ccf356ef-eca6-43cb-a408-280198fffed2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhG2sefNnOcLL33JnqGX4w4FSucEcm60J4xxHbTMb9HbvhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOv7Ib+sDdhHE$$panel$$_blank']</value>
      <webElementGuid>71913344-93cb-41ab-bd59-dca3689bc13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[3]</value>
      <webElementGuid>2330fc9d-0326-4ce2-a08d-9e3f2b39ecd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]</value>
      <webElementGuid>28dd8c7f-62a9-49b6-a484-eb93312a9470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhG2sefNnOcLL33JnqGX4w4FSucEcm60J4xxHbTMb9HbvhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOv7Ib+sDdhHE$$panel$$_blank' and (text() = 'View details for: emp  03 ' or . = 'View details for: emp  03 ')]</value>
      <webElementGuid>a6e0f505-12c0-4373-a39a-7a66a09be3b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
