<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  07</name>
   <tag></tag>
   <elementGuidId>edbe6593-c599-4e31-908f-d73bd5c0149a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhdac9p97oLSf33JnqGX4w4FSucEcm60J4WQ+oILBfUFKAc4R8O4Uf40HiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOi39%2F6kK06bq$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a853d37c-8805-4f29-8497-a4350c878bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhdac9p97oLSf33JnqGX4w4FSucEcm60J4WQ+oILBfUFKAc4R8O4Uf40HiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOi39%2F6kK06bq$$panel$$_blank</value>
      <webElementGuid>7be7a8c5-b48a-4553-b1cc-03266fb0c67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>dcda2f40-201d-46c7-a318-a5ce6d74b841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  07 </value>
      <webElementGuid>61af4838-0d1d-42be-92f6-c21816605ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhdac9p97oLSf33JnqGX4w4FSucEcm60J4WQ+oILBfUFKAc4R8O4Uf40HiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOi39%2F6kK06bq$$panel$$_blank&quot;)</value>
      <webElementGuid>1e6df595-0737-4716-ad71-e9f19e65c462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhdac9p97oLSf33JnqGX4w4FSucEcm60J4WQ+oILBfUFKAc4R8O4Uf40HiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOi39%2F6kK06bq$$panel$$_blank']</value>
      <webElementGuid>eeca2c51-4628-48e2-80fd-4dc06b39084c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[7]</value>
      <webElementGuid>8d01872e-496b-4cac-80a9-cf5fe850f375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[7]</value>
      <webElementGuid>a9715dc2-bafc-48bd-bc49-8f7f85819497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhdac9p97oLSf33JnqGX4w4FSucEcm60J4WQ+oILBfUFKAc4R8O4Uf40HiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOi39%2F6kK06bq$$panel$$_blank' and (text() = 'View details for: emp  07 ' or . = 'View details for: emp  07 ')]</value>
      <webElementGuid>2a7ae7b4-c423-4711-8857-8d9f227686ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
