<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  05</name>
   <tag></tag>
   <elementGuidId>07f840aa-596c-4f9a-abf6-a93cfd3740f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhJAaiCo2NbTH33JnqGX4w4FSucEcm60J4iaA571kAZVw5N7SBJjRxJEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOu49aLBCKmq9$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3662cfc7-8a40-4495-a9b4-09700bb924e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhJAaiCo2NbTH33JnqGX4w4FSucEcm60J4iaA571kAZVw5N7SBJjRxJEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOu49aLBCKmq9$$panel$$_blank</value>
      <webElementGuid>dcd6600f-feb5-4ea4-8a62-a92f74e50d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>c1d0c93c-9be9-4159-8274-debdaf32756c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  05 </value>
      <webElementGuid>db9bdfe7-a45b-4b4c-aa0f-b6e3855bef18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhJAaiCo2NbTH33JnqGX4w4FSucEcm60J4iaA571kAZVw5N7SBJjRxJEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOu49aLBCKmq9$$panel$$_blank&quot;)</value>
      <webElementGuid>9f26021e-5a7a-4c07-b474-ac8a1eefc077</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhJAaiCo2NbTH33JnqGX4w4FSucEcm60J4iaA571kAZVw5N7SBJjRxJEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOu49aLBCKmq9$$panel$$_blank']</value>
      <webElementGuid>3d2ec22f-4c1d-4318-b988-392cc939b44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[5]</value>
      <webElementGuid>d7e1eca0-eede-46f3-bf14-51b6c9be25e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[5]</value>
      <webElementGuid>b98269b8-1019-47ca-9ee3-6b2d4b8c36fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhJAaiCo2NbTH33JnqGX4w4FSucEcm60J4iaA571kAZVw5N7SBJjRxJEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOu49aLBCKmq9$$panel$$_blank' and (text() = 'View details for: emp  05 ' or . = 'View details for: emp  05 ')]</value>
      <webElementGuid>156d90cf-fc7a-461d-a619-a031bae0ab76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
