<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  08</name>
   <tag></tag>
   <elementGuidId>3a66d9d4-af56-4396-8c88-c4107255dc4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh3Xc6r4owfDH33JnqGX4w4FSucEcm60J4WyK+c4P37OfhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqdR%2F6meRZ5g$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ffa80b64-491b-43a0-9477-faf323e560b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh3Xc6r4owfDH33JnqGX4w4FSucEcm60J4WyK+c4P37OfhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqdR%2F6meRZ5g$$panel$$_blank</value>
      <webElementGuid>58488e8a-72c8-422b-ae70-ae36b4671410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>35c2c97c-cf66-4852-8a16-b681504a82b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  08 </value>
      <webElementGuid>3b353160-10c7-4a1d-a395-1305ee5cb80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh3Xc6r4owfDH33JnqGX4w4FSucEcm60J4WyK+c4P37OfhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqdR%2F6meRZ5g$$panel$$_blank&quot;)</value>
      <webElementGuid>fb768af5-774c-4f74-9d3d-0b6884ff8188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh3Xc6r4owfDH33JnqGX4w4FSucEcm60J4WyK+c4P37OfhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqdR%2F6meRZ5g$$panel$$_blank']</value>
      <webElementGuid>4a2a5b4e-866d-43e5-bca0-ed0a385eea68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[8]</value>
      <webElementGuid>b68ed769-7ac2-41c8-8e17-ed61ee8793ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[8]</value>
      <webElementGuid>012cf237-010a-45ec-b6e5-846866591927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh3Xc6r4owfDH33JnqGX4w4FSucEcm60J4WyK+c4P37OfhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqdR%2F6meRZ5g$$panel$$_blank' and (text() = 'View details for: emp  08 ' or . = 'View details for: emp  08 ')]</value>
      <webElementGuid>cce15aa5-9821-4b35-8e5b-d3cfef205630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
