<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  09</name>
   <tag></tag>
   <elementGuidId>220b0562-8d9c-4e2e-af3b-10b7c08cdac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhPX85okHfLJb33JnqGX4w4FSucEcm60J47g7eM36D7+bhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOr1B7CUOHPNj$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53f5b9d7-81f3-4378-91e5-d66ea6650b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhPX85okHfLJb33JnqGX4w4FSucEcm60J47g7eM36D7+bhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOr1B7CUOHPNj$$panel$$_blank</value>
      <webElementGuid>af02304e-d109-4e05-969a-bb3a8f46b310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>fecca0a5-a3d4-4f4e-bf6c-c31c6b661421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  09 </value>
      <webElementGuid>9643621f-6f55-4cc5-a14e-843674bb09cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhPX85okHfLJb33JnqGX4w4FSucEcm60J47g7eM36D7+bhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOr1B7CUOHPNj$$panel$$_blank&quot;)</value>
      <webElementGuid>6da66514-8026-455d-9444-6e4ed8cea209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhPX85okHfLJb33JnqGX4w4FSucEcm60J47g7eM36D7+bhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOr1B7CUOHPNj$$panel$$_blank']</value>
      <webElementGuid>bafd6c1c-edf1-4ff1-86dd-403a305127e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[9]</value>
      <webElementGuid>b001c7c7-4c32-445e-880f-14cc85be919d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[2]</value>
      <webElementGuid>1c2aa5f5-78e8-45d5-8550-0046b4e7f350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[9]</value>
      <webElementGuid>6f53207d-fdd3-43a3-a040-4d98cacddd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhPX85okHfLJb33JnqGX4w4FSucEcm60J47g7eM36D7+bhKqiBTa6mdEHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOr1B7CUOHPNj$$panel$$_blank' and (text() = 'View details for: emp  09 ' or . = 'View details for: emp  09 ')]</value>
      <webElementGuid>f12e4ae5-7082-40cf-beeb-99a51e999eed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
