<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  06</name>
   <tag></tag>
   <elementGuidId>fe125f7e-f6fc-4adb-b81d-78c6bc901c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh9500ZbLt4iH33JnqGX4w4FSucEcm60J4sN2ag838UFnEL4Ni%2FTE%2FcUHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOjsgmYAj7WkI$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d84be8a0-035f-4c1d-b4cd-1204aecd5cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh9500ZbLt4iH33JnqGX4w4FSucEcm60J4sN2ag838UFnEL4Ni%2FTE%2FcUHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOjsgmYAj7WkI$$panel$$_blank</value>
      <webElementGuid>69c2c17e-0715-4f9b-b032-20fc202956e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>d5702221-ae21-4b97-b242-d2d8ec29fe8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  06 </value>
      <webElementGuid>b06a98ce-648f-475b-9919-4eb45652851e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh9500ZbLt4iH33JnqGX4w4FSucEcm60J4sN2ag838UFnEL4Ni%2FTE%2FcUHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOjsgmYAj7WkI$$panel$$_blank&quot;)</value>
      <webElementGuid>207a7ea2-3ce1-4074-a1e8-1750f1812640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh9500ZbLt4iH33JnqGX4w4FSucEcm60J4sN2ag838UFnEL4Ni%2FTE%2FcUHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOjsgmYAj7WkI$$panel$$_blank']</value>
      <webElementGuid>3e540392-b6dc-4020-94b0-000f64c9bd15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[6]</value>
      <webElementGuid>5635d4b8-4ca2-4131-887f-564830bd2813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[6]</value>
      <webElementGuid>ae261e2b-91d7-469a-9690-b5cacd7eaf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh9500ZbLt4iH33JnqGX4w4FSucEcm60J4sN2ag838UFnEL4Ni%2FTE%2FcUHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOjsgmYAj7WkI$$panel$$_blank' and (text() = 'View details for: emp  06 ' or . = 'View details for: emp  06 ')]</value>
      <webElementGuid>264d1ecf-3f96-4ce2-aee0-5d4f3f1b93cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
