<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_moduleName</name>
   <tag></tag>
   <elementGuidId>af4589f1-dea4-409f-8927-4cabefb116fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='moduleNameId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#moduleNameId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27ac3b8f-02b7-4a43-926a-1968e552695d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>moduleName</value>
      <webElementGuid>472d1e76-07ca-42a1-b07f-ab5c71b972a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>84px</value>
      <webElementGuid>6481efb3-2153-430f-9db3-b2898159c5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-logobar form-control </value>
      <webElementGuid>68457295-2f3b-4633-8a72-181af5dd2015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>ajax_showOptions(this, 'getEmployeesByLetters', event, 'advancedFeatureSearch')</value>
      <webElementGuid>6333f1a0-0713-4d3c-9730-f432face25b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>92fbdcfd-eaf2-4fdb-8b5f-a5e2d5f73c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moduleNameId</value>
      <webElementGuid>538474b6-c079-4010-853b-ae2f330be1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18b8daac-2838-4a2f-a672-ee72e2ef9243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a feature or employee name (@name)</value>
      <webElementGuid>144c97bd-061c-4d89-aef7-aea829f62725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleNameId&quot;)</value>
      <webElementGuid>aaf30134-2c41-455b-91e1-7203278b1de8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='moduleNameId']</value>
      <webElementGuid>cfe7be30-18de-4432-a577-0c4ccc6ab2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cd-primary-nav']/li/div/div/input</value>
      <webElementGuid>90e03b56-c3bb-4a61-a69a-e891f738dec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/input</value>
      <webElementGuid>b82e2b57-9291-48cc-98f7-cbbf70d6e146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'moduleName' and @id = 'moduleNameId' and @type = 'text' and @placeholder = 'Search a feature or employee name (@name)']</value>
      <webElementGuid>7b62134b-97fc-4c88-9b66-6c4e30d32c10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
