<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Good morningemp,</name>
   <tag></tag>
   <elementGuidId>e27fdeb4-53b2-4a71-a893-239c3377240d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.font_display_medium_bold.welcome-h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='displayPageContent']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b1894f7-5ca6-41df-9c13-57ab0a313ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font_display_medium_bold welcome-h1</value>
      <webElementGuid>a0bc68e1-4ca3-4b39-a863-926a99369252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Good morning emp, </value>
      <webElementGuid>7385a64c-16bc-4491-914a-05140c729b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayPageContent&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;v10-content-section&quot;]/div[@class=&quot;col-md-9 col-sm-12&quot;]/div[@class=&quot;font_display_medium_bold welcome-h1&quot;]</value>
      <webElementGuid>c58bdfb6-b8c2-4051-9c3c-6d3b693cea52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC01 - Login/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>2d9b068f-d607-4235-b4b4-b6477a645e51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div/div[2]/div/div</value>
      <webElementGuid>c4cfad93-386e-421d-959e-aefb013aa9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tue 30 Jan, 11:36 AM'])[1]/preceding::div[2]</value>
      <webElementGuid>9d32bc97-f6be-47e8-bf5c-6e57bac1478a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>e9239cb5-2d9f-432c-b230-12dec40f94d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Good morning emp, ' or . = 'Good morning emp, ')]</value>
      <webElementGuid>fca4890c-4c83-4883-a719-549e8ed1aa76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
