<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame</name>
   <tag></tag>
   <elementGuidId>976a1f87-91fc-46a8-aa4c-a578228f0995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d457f462-7bc1-474e-ae30-c2a8762c2e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>3d8bbe97-af8e-4653-8aba-36c0f9810afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>6bd77988-3808-4f43-906e-ad7ced911c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>31e6fccb-e476-438a-8c31-ddbad2c7236c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>151d879e-522c-4713-80b1-f3fa7cf003fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5a418c7a-5504-479f-94c1-20965732e4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>7b895ec7-edf2-4ea3-a700-d905179c1467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>db341a9a-bd55-42f7-abb0-a4c5329f8804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>809d1511-a942-4d07-b70e-afb34bb10086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>26b041f8-52fd-4d98-b2dd-dc00bb77c10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>6b0222fa-7323-4ba4-9d68-02400de9f648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>2bf52832-e09f-4cf4-b240-8f6482b61042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
