<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Manager services_homePageFrame</name>
   <tag></tag>
   <elementGuidId>efcc38be-3ec2-4dc5-a132-9581f9325d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9878281b-b48a-449e-a3cb-769f1c602435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBdUFDXpThWC3B+7y60b6oPaWcSp2oTaYHT7XIl8hsJFEMoT5xKz7rWCmm98XBirJGaMYtbEkBoSra8p0bqpWijYx9okq%2FKQ7WsJyBT9oQ1O+sJGJR7NcsOm8D5hwi8WTeVuj772PwqrT3d0VCO2uHEh</value>
      <webElementGuid>c6762d1b-f433-4d73-ab5f-f991b49a16eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>8b3a55c9-2b44-4413-aba2-7df1598b006f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>d8ef42b7-900a-41ae-a595-f07419902b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>e3465892-dc2b-4ee0-b49f-45e5ed67ab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>3a4111c2-b5f9-4874-b08a-fc66a1cdf54e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>dc7708c8-3868-48a8-a24f-384af92ca7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>b5b5ebc7-9405-43f9-a8aa-03a26625fb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>20aff24e-e99f-4566-a896-9d4e0312c599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBdUFDXpThWC3B+7y60b6oPaWcSp2oTaYHT7XIl8hsJFEMoT5xKz7rWCmm98XBirJGaMYtbEkBoSra8p0bqpWijYx9okq%2FKQ7WsJyBT9oQ1O+sJGJR7NcsOm8D5hwi8WTeVuj772PwqrT3d0VCO2uHEh' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>d980bb59-d7e3-44e9-9041-99786ee63012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
