<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_chatMessageContent</name>
   <tag></tag>
   <elementGuidId>54990181-eef7-4bde-b167-f0e66ff6ca16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chatMessageContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='chatMessageContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c6d5b711-2e85-40f4-af96-dea2a0f4bd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chatMessageContent</value>
      <webElementGuid>10642c7d-a73a-44b1-b887-e57cec175d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>f620d359-c631-4174-bb19-c7db374d27f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>55497a3b-4e31-4a8a-8df5-b6bf66ef7eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d33c9b0c-9af4-4a82-a2ba-338a44be0392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d6315195-b083-4404-8b7b-93e4bdead257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chatMessageContent&quot;)</value>
      <webElementGuid>7fb485d4-7fe9-4dfb-81b5-012e50deb107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='chatMessageContent']</value>
      <webElementGuid>3c04198e-2374-41e6-a079-79637b4ec487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div[4]/textarea</value>
      <webElementGuid>4bf31ba1-756e-4dcc-8432-da149e309009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cf0376f1-7832-40bb-a1e6-add5a89ed8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'chatMessageContent']</value>
      <webElementGuid>be92c554-0740-4817-9e31-7f0b2f94b1f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
