<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please specify the old password</name>
   <tag></tag>
   <elementGuidId>92a9ea39-70d7-470e-9085-8dad4b028543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bootstrap-dialog-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Please specify the old password.' or . = 'Please specify the old password.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bcbb3873-c7e8-4575-a2f8-c925f61fb511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bootstrap-dialog-message</value>
      <webElementGuid>00316a9e-5346-4853-8972-f0235c3da893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please specify the old password.</value>
      <webElementGuid>5ed636d2-8853-4f3a-8703-087ced4d500d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b0a2b8ed-6976-4ac4-8c27-b1dd01082f28&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;bootstrap-dialog-body&quot;]/div[@class=&quot;bootstrap-dialog-message&quot;]</value>
      <webElementGuid>e3bb9c17-88d3-496e-afc7-05d1eabbf584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC07 - User Profile Icon/TC_068_UpdateBlankPassword/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>1eb439c4-4eae-41b1-b456-a5961d9030da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b0a2b8ed-6976-4ac4-8c27-b1dd01082f28']/div/div/div[2]/div/div</value>
      <webElementGuid>b1fdc408-4e2c-40e5-a74e-9d9674f72baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[3]</value>
      <webElementGuid>2abb9b1c-89d4-47fd-ab07-019c748d4511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::div[4]</value>
      <webElementGuid>f5d055ed-9a03-44dc-987c-bc59baff2ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[1]</value>
      <webElementGuid>87e4fc31-27a5-4069-a9c1-eef9e601e31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please specify the old password.']/parent::*</value>
      <webElementGuid>2a13600d-e64e-4fdc-b1cc-a593b1572364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>7e312e2b-a0d9-4b05-b191-a4a98ffb9728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Please specify the old password.' or . = 'Please specify the old password.')]</value>
      <webElementGuid>bdc8aca6-ca9b-49c9-9530-a9b962e85257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
