<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Real ke ni</name>
   <tag></tag>
   <elementGuidId>4922f18f-a79c-4adf-a96a-fdfa82e2deef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editFeedResponse_1000012_1000049</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='editFeedResponse_1000012_1000049']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${comment}' or . = '${comment}') and @ref_element = 'Object Repository/TC04 - Dashboard/02 - Feed/TC_017_AddComment/Page_Home page/iframe_Self services_homePageFrame (3)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3375b9ac-03b0-4af1-8ca9-2e89fbe6a54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editFeedResponse_1000012_1000049</value>
      <webElementGuid>dd9f0135-2d42-476f-ab5c-37c4b6b72db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${comment}</value>
      <webElementGuid>711bc4eb-7171-4177-b04c-47956e75ad58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editFeedResponse_1000012_1000049&quot;)</value>
      <webElementGuid>eafdea0a-cf58-4cf2-a5fd-9c4af5281bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/02 - Feed/TC_018_ExpandCommentSection/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>9737ecc0-0a15-45a8-8b70-dfa20935f8bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='editFeedResponse_1000012_1000049']</value>
      <webElementGuid>10eb30b9-4abd-4c81-9cb8-333b021f1cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='viewFeedResponse_1000012_1000049']/div/div[2]/span</value>
      <webElementGuid>2199ed9f-ac5c-4dde-8116-c67737f707e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 01'])[1]/following::span[1]</value>
      <webElementGuid>1325ca96-8fb7-486d-be72-8f93bdddc8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 04'])[1]/preceding::span[1]</value>
      <webElementGuid>ad707f54-c4a6-4c43-befc-1b67411742fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🎉'])[1]/preceding::span[1]</value>
      <webElementGuid>8e9c034b-ed31-4b68-82c1-2a840ac1ac4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Real ke ni?']/parent::*</value>
      <webElementGuid>089278e7-a803-41c1-b8b1-41fad19272b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/span</value>
      <webElementGuid>d4fd00a9-5939-43b1-8852-9a843b92407c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'editFeedResponse_1000012_1000049' and (text() = 'Real ke ni?' or . = 'Real ke ni?')]</value>
      <webElementGuid>7830195d-d2e4-4b25-8e10-f4cc5a8ed90d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
