<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cancelled</name>
   <tag></tag>
   <elementGuidId>b6bd7801-c09e-4ba9-8eca-f038e6e416f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.li_pending</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='renderTableHeaderArray']/tbody/tr/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>782b9fc3-5cee-445e-b219-1a6d6f1aa3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>li_pending</value>
      <webElementGuid>624cdfc5-13f8-4514-801c-7e5765a2c5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelled</value>
      <webElementGuid>865d5a4e-b9f9-4e8e-992e-c80c01e7aa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewEmpLeaveRequest&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;personalprofile&quot;]/div[@id=&quot;renderTable-scroll&quot;]/table[@id=&quot;renderTableHeaderArray&quot;]/tbody[1]/tr[@class=&quot;last-row&quot;]/td[2]/span[@class=&quot;li_pending&quot;]</value>
      <webElementGuid>a52befad-666c-4ae4-a550-4800754cd259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/02 - Leave/TC_046_CancelPendingLeaveReq/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>b194ba16-38ac-4d5c-b6b4-3094d577c6be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='renderTableHeaderArray']/tbody/tr/td[2]/span</value>
      <webElementGuid>e61aefd6-d190-4e49-9df3-6b4aae413e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sick Leave for 1.0 day On 30-Dec-23 applied on 26/12/2023'])[1]/following::span[1]</value>
      <webElementGuid>f8e38c4e-e731-499b-9097-e9ee57efad9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave requests'])[1]/following::span[1]</value>
      <webElementGuid>9cbe1c67-1a3a-4c6f-a4c5-44b0b6f33763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[4]/preceding::span[2]</value>
      <webElementGuid>e04f3ed1-ab40-4335-9857-f4dbefd5acbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::span[3]</value>
      <webElementGuid>a25e61ce-84d0-4c3d-afed-345a99ae9510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancelled']/parent::*</value>
      <webElementGuid>a776b64e-d323-444e-a6f8-eaa21902617d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>2912847f-f2fa-434e-b998-0c17c747cf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cancelled' or . = 'Cancelled')]</value>
      <webElementGuid>3c5f06db-b830-4cf3-8bba-30b5ed9c6c6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
