<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp  07</name>
   <tag></tag>
   <elementGuidId>faa13332-45e7-4293-bd33-c30040f41058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1003783</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1003783']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;1003783&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2925dac4-0a2e-495e-99c4-4820ff44cfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1003783</value>
      <webElementGuid>1a001999-7522-40b2-9004-85abd93e029d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>c1a546b6-3a09-487d-be02-9a6f7ab15f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${empName}</value>
      <webElementGuid>26c708e6-9257-46b2-a4bc-41e22b817530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1003783&quot;)</value>
      <webElementGuid>c7616d95-9745-4940-84be-87ce5afeda27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1003783']</value>
      <webElementGuid>df21a0e1-2f21-4695-9e93-7b1ef781c5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[7]</value>
      <webElementGuid>830a0748-36bf-4bed-a24a-111a9f28afd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[7]</value>
      <webElementGuid>0d1e196f-6952-4f1f-b07f-c3f38d243a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1003783' and (text() = 'emp  07 ' or . = 'emp  07 ')]</value>
      <webElementGuid>128cb221-f5a5-4364-b89a-c1976a982566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
