<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rating_pulseRating_3</name>
   <tag></tag>
   <elementGuidId>0cd201ab-8b1b-46a8-8a6c-d44085b8cfd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pulseRating_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pulseRating_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>75a2b6c4-0946-4033-9a1c-920b60852821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/client/tenant-lite/blankStarRating.gif</value>
      <webElementGuid>f58c3cc3-bb34-4492-8ece-9ff41b13580a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>4.0</value>
      <webElementGuid>f7668f76-5778-4296-804e-55214877424e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulseRating_3</value>
      <webElementGuid>5804d9c0-05fc-4d98-a4b0-b89e4d4b15a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStarRatingOptions('pulseRating','3','5','4.0');setChanged();</value>
      <webElementGuid>14c8098f-ecd7-496f-8591-00478fc2e019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulseRating_3&quot;)</value>
      <webElementGuid>f569acea-5352-4d7d-a1dc-6f9c32e57cd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pulseRating_3']</value>
      <webElementGuid>479ce2e1-6081-4755-8507-554aced73eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[3]/div/img[4]</value>
      <webElementGuid>f1ce0f66-b8b0-401e-ad1c-6975fdde4b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='4.0']</value>
      <webElementGuid>a8caf87f-d6e1-4636-ac43-9c1f0d33d989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[4]</value>
      <webElementGuid>8057662e-fe51-4bf8-a5b2-dc513c53f3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/client/tenant-lite/blankStarRating.gif' and @title = '4.0' and @id = 'pulseRating_3']</value>
      <webElementGuid>01366522-ffca-4d7a-8ac4-2b8801d30043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
