<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rating_pulseRating_0</name>
   <tag></tag>
   <elementGuidId>80b10be6-8c81-44f6-9de2-70d91b085ebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pulseRating_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pulseRating_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f9878a44-d34f-4683-a368-4264fda98d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/client/tenant-lite/blankStarRating.gif</value>
      <webElementGuid>6cf724ce-a0a1-4067-8ccf-8db256905cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1.0</value>
      <webElementGuid>87d5cf90-02de-470b-a18a-48b83249cb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulseRating_0</value>
      <webElementGuid>40fa111d-8b5f-4409-b84c-e555794ee05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStarRatingOptions('pulseRating','0','5','1.0');setChanged();</value>
      <webElementGuid>91a433dd-d2a4-48c9-9537-5eba8e332628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulseRating_0&quot;)</value>
      <webElementGuid>6198e4d6-6bc7-485b-8afb-eed6956c3092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pulseRating_0']</value>
      <webElementGuid>7fda9e34-f892-4ae9-b439-e6f61318ee55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[3]/div/img</value>
      <webElementGuid>ecf8007b-45be-483d-b499-b3bd2914d78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='1.0']</value>
      <webElementGuid>169f842e-aa9d-46f1-8212-2b343c9daf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>af16d8f9-957d-4ea3-a63b-79de6cab0db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/client/tenant-lite/blankStarRating.gif' and @title = '1.0' and @id = 'pulseRating_0']</value>
      <webElementGuid>e2c3aeea-40a6-4702-84ca-8abff752f4b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
