<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rating_pulseRating_2</name>
   <tag></tag>
   <elementGuidId>65f986f6-6915-4b3c-836d-c217f2103ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pulseRating_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pulseRating_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a81f3c2f-3999-4219-b66a-434295f588d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/client/tenant-lite/blankStarRating.gif</value>
      <webElementGuid>28f95fdb-8930-4081-93fd-065bccf7c8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3.0</value>
      <webElementGuid>c4a1e377-c204-4681-a1c9-d4f2dda337bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulseRating_2</value>
      <webElementGuid>2a1385b0-e3de-453c-877b-27c2b1b27f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStarRatingOptions('pulseRating','2','5','3.0');setChanged();</value>
      <webElementGuid>6a05e326-fed6-42de-ac7b-bdd825f556b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulseRating_2&quot;)</value>
      <webElementGuid>5e52c70e-daed-459e-8101-58d9153e9b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pulseRating_2']</value>
      <webElementGuid>96d4f9ef-9eea-435b-99d9-5572529b4695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[3]/div/img[3]</value>
      <webElementGuid>fbf27203-f03c-41cc-9351-0dc5ecf9c939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='3.0']</value>
      <webElementGuid>c363895d-0f24-4ecd-b9a6-7cdce832d4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[3]</value>
      <webElementGuid>5afa9824-5f72-4a49-ba42-6bc7d5bbf420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/client/tenant-lite/blankStarRating.gif' and @title = '3.0' and @id = 'pulseRating_2']</value>
      <webElementGuid>78dadd00-a8ec-47f2-b79f-e9e897760b16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
