<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Self services side bar</name>
   <tag></tag>
   <elementGuidId>e1837a05-41e4-44a6-b029-d2b33a34d6fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transact_txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Self services']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e0c2040-67f9-4fe6-bc35-6b5d17be34d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transact_txt</value>
      <webElementGuid>ffe4fa84-95b4-47e6-9190-f986729718af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font_text_x-small v10-side-menu-text sel</value>
      <webElementGuid>f33461f8-f116-45ac-9780-a4bd0b75b548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self services</value>
      <webElementGuid>e4c333d1-a97a-4952-b34d-a440e9358ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transact_txt&quot;)</value>
      <webElementGuid>64caf0f0-45d6-4f46-8f98-1ed743ebcfa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='transact_txt']</value>
      <webElementGuid>04b83cca-cfd1-424e-9471-518bc01818c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transact']/div[2]</value>
      <webElementGuid>4dc43b36-fd2f-46d6-a15a-e609a06c5af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[3]</value>
      <webElementGuid>721e25b5-cba4-4d0e-bd33-718d31baf962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::div[33]</value>
      <webElementGuid>115debeb-49b6-49f7-8b7d-3274167a19de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/preceding::div[42]</value>
      <webElementGuid>23e2c689-c600-46a0-8353-9bc2f95695e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Self services']/parent::*</value>
      <webElementGuid>f63abf3a-fc14-4621-9964-f483eeb04b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>0cfac7a2-7f7f-48ea-bc6c-99887dc78023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'transact_txt' and (text() = 'Self services' or . = 'Self services')]</value>
      <webElementGuid>73d73e19-ba46-4b30-8d95-5e1a6ca9ff32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
