<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_My profile preview</name>
   <tag></tag>
   <elementGuidId>c9190c3c-9038-4d83-a02e-0317cdff6cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayEmpPersonalDetail_headerV10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id = 'displayEmpPersonalDetail_headerV10' and (text() = ' My profile' or . = ' My profile')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>38dd7f54-6731-4e7c-8aa8-cd272b2d373f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayEmpPersonalDetail_headerV10</value>
      <webElementGuid>509d7ef4-f2ae-4b40-bf7e-882e9f089579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10widget-tite-font</value>
      <webElementGuid>4a9d1c15-1a7d-49d5-b16a-a4780cd64489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> My profile</value>
      <webElementGuid>55651103-4e4b-40e8-af59-6c3d2fb724e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayEmpPersonalDetail_headerV10&quot;)</value>
      <webElementGuid>f2074129-0da5-41a4-b142-ba9f4b4be6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/01 - Profile/TC_040_ViewProfile/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>1d93bf78-f46b-4f80-9bb7-dbb450b6c3e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='displayEmpPersonalDetail_headerV10']</value>
      <webElementGuid>b5a83952-4bfe-4641-a60a-4b21f7f9633e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='head-areaV10']/h2</value>
      <webElementGuid>f1583cdc-ceca-4a51-bcef-a99b841a24ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My profile']/parent::*</value>
      <webElementGuid>e9dd6d5a-9813-4e83-ad96-9f3aae77c4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>a70a3be4-cf30-4ffa-8369-d395531fd8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'displayEmpPersonalDetail_headerV10' and (text() = ' My profile' or . = ' My profile')]</value>
      <webElementGuid>2f0c2bde-543a-48c3-a034-ea354c298e4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
