<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Self services_homePageFrame</name>
   <tag></tag>
   <elementGuidId>5bd3bda3-51dd-4252-bbd9-6a68d8d39d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5a8ac28b-86c5-48cc-848a-7d10d889570a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=ik9tw87AIxz0HrZJkp%2Fiacs4tovwWogXVBQ16U4Vgtwfu8utG+qD2lnEqdqE2mB0AcYMnd+0iXs%3D</value>
      <webElementGuid>751d32da-ad94-4f58-88a8-d78692924e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>83a4b909-5bf4-44c3-9840-6a11677bca5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>77c59a65-66c1-4940-ad64-7afd5cc50e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>448926a0-92e0-4ee2-99f3-faad42c64b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>7ea7b0e1-91be-46fa-9532-1ee2e1e91943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>c0a40d48-9436-41ec-b469-fe57463949f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>95ab34a0-9d01-4f0e-9180-f49207dd0c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>44165f72-48b1-4534-80ec-d849c49a3d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=ik9tw87AIxz0HrZJkp%2Fiacs4tovwWogXVBQ16U4Vgtwfu8utG+qD2lnEqdqE2mB0AcYMnd+0iXs%3D' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>8f189d75-f953-4bea-8f5b-57a8df4edc99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
