<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date</name>
   <tag></tag>
   <elementGuidId>4c76a41b-93d5-4769-ad46-8b0caeac6998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a0fe21a-71db-47dc-a383-c8350b12e1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>90d42367-70a7-496c-addb-0577e605e288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f47b3b8-5aab-46da-ad1d-fc946726ce60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_dataObject.endDate</value>
      <webElementGuid>b71e79f0-975c-4934-97cc-bbea3d75c980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>05b3bacf-b386-4baf-b57b-f5675bfe895f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>834f4209-80ea-4317-a618-a92175c3bd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:calculateDays('Yes', '');return false;</value>
      <webElementGuid>69b1b774-5f06-4da8-906c-70bdc1514974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>End date</value>
      <webElementGuid>d98d0619-be7b-4e6d-9a6b-dc9947d177e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endDate&quot;)</value>
      <webElementGuid>cda90d92-86ef-4199-a40c-836983c779bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/03 - Leave/TC_031_ApplySickLeave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>d77700ab-e007-461d-b19e-7f5109e37758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endDate']</value>
      <webElementGuid>a5c34883-f97b-42f6-81a2-2acefb1fbfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='durationCtr']/div[2]/input</value>
      <webElementGuid>093041dc-aabd-4c35-abc9-c4760f3676aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/input</value>
      <webElementGuid>edc6c38d-6fe5-4cb6-90fb-cbd5cfe382e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date_dataObject.endDate' and @id = 'endDate' and @placeholder = 'End date']</value>
      <webElementGuid>4c75ca8e-5666-4e32-82fe-0e23ea965de3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
