<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If checked, login details will not be_5c5f06</name>
   <tag></tag>
   <elementGuidId>d2c4725e-dea8-457a-8393-5c0060748aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cf4336b-50ea-45a8-ba5d-360f5abebefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c5b593de-4677-4a7b-879b-9858cece922e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c789a7d7-c489-43b5-98d9-f12d15f330ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aecabbe3-9e65-4072-b042-4e664b79b6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pId</value>
      <webElementGuid>a13f2837-0765-4e0a-adfd-e55496487d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box lock</value>
      <webElementGuid>72df0274-c7b1-4872-b7b0-7b70cdfb8e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:detect_Key(event);</value>
      <webElementGuid>4135e658-2981-4984-ba34-4e6765f61342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>document.logonForm.password.select();</value>
      <webElementGuid>5bed0dba-b7f3-4ec8-84bb-4fe07a32178e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pId&quot;)</value>
      <webElementGuid>6e8e41a0-df99-4517-9f9b-82ca55e99aff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pId']</value>
      <webElementGuid>43f9d8e9-6eb1-43a5-a4f4-130d86ebf6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>ee5d143e-4d58-4440-8b14-94687d8b0965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @name = 'password' and @id = 'pId']</value>
      <webElementGuid>39149eb1-7ec4-421a-b045-ac92db016560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
