<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If checked, login details will not be_5dd927</name>
   <tag></tag>
   <elementGuidId>c87c3938-3cf0-45ad-bf4a-09b8de979982</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usr_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usr_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a032c11c-c2d5-446b-8fc7-5589543fc796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5c42bc2-5411-4009-bd5e-096a8bf0aa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box userLogin</value>
      <webElementGuid>44061356-9215-4cde-952a-b03e663575b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empNo</value>
      <webElementGuid>b9ed4845-d801-4bbc-81af-bd41efeb2dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name</value>
      <webElementGuid>195e1d24-1fb6-481c-8801-1cb112c19c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:detect_Key(event);</value>
      <webElementGuid>50a08a32-843f-4e2e-b885-e0a57ecee7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>document.logonForm.empNo.select();</value>
      <webElementGuid>0c13d9d9-5471-4d4c-a9d4-977af610fa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usr_1</value>
      <webElementGuid>99375476-c8fa-4bfc-8134-b5e09520eb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usr_1&quot;)</value>
      <webElementGuid>1c5773ce-ae0d-4015-b184-3ed79b3d199b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usr_1']</value>
      <webElementGuid>40188394-5623-4af5-a240-ba1a7bb8155f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5d6943b8-6917-4114-920f-75d4c2b945de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empNo' and @placeholder = 'User name' and @id = 'usr_1']</value>
      <webElementGuid>cd5c25d5-1e30-43fd-966d-e3f910155256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
