<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_006_Leave</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8a5cbfc5-1a6d-471e-bb63-89633005fe53</testSuiteGuid>
   <testCaseLink>
      <guid>41a5e0a1-0d13-48a4-b82e-c0c3b6994794</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Dashboard/03 - Leave/01 - Positive/TC_026_ApplyCasualLeave</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f536f59-8429-4c27-ba03-e888e61ceead</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae911c0-c3a8-4bd4-9d2b-9ca5600727a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91481de3-0433-4c60-a29d-74dfad4a1200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12391c2-d2ed-4fa8-8061-00ae3023d6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b02968-afc1-42c9-8e28-0e55f63f4284</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>279debf2-b953-41eb-9f58-85f8fd7b1621</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Dashboard/03 - Leave/01 - Positive/TC_027_ApplyHalfDAyCasualLeave</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f536f59-8429-4c27-ba03-e888e61ceead</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae911c0-c3a8-4bd4-9d2b-9ca5600727a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91481de3-0433-4c60-a29d-74dfad4a1200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12391c2-d2ed-4fa8-8061-00ae3023d6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b02968-afc1-42c9-8e28-0e55f63f4284</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a575f2a5-654b-464a-9286-1c61989c1aba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Dashboard/03 - Leave/02 - Negative/TC_028_CasualLeaveUnsuccess</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f536f59-8429-4c27-ba03-e888e61ceead</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae911c0-c3a8-4bd4-9d2b-9ca5600727a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91481de3-0433-4c60-a29d-74dfad4a1200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12391c2-d2ed-4fa8-8061-00ae3023d6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b02968-afc1-42c9-8e28-0e55f63f4284</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>082ef621-da67-423d-8307-225e7e0980f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Dashboard/03 - Leave/02 - Negative/TC_029_BothHalfDayTicked</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f536f59-8429-4c27-ba03-e888e61ceead</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae911c0-c3a8-4bd4-9d2b-9ca5600727a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91481de3-0433-4c60-a29d-74dfad4a1200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12391c2-d2ed-4fa8-8061-00ae3023d6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b02968-afc1-42c9-8e28-0e55f63f4284</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7c181f5-f113-4188-a145-ecfb0a4e4af8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Dashboard/03 - Leave/02 - Negative/TC_030_EarnedLeaveFail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f536f59-8429-4c27-ba03-e888e61ceead</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae911c0-c3a8-4bd4-9d2b-9ca5600727a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91481de3-0433-4c60-a29d-74dfad4a1200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12391c2-d2ed-4fa8-8061-00ae3023d6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b02968-afc1-42c9-8e28-0e55f63f4284</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f44ff2f-73f5-4245-b890-f53ef5d973ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Dashboard/03 - Leave/01 - Positive/TC_031_ApplySickLeave</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f536f59-8429-4c27-ba03-e888e61ceead</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae911c0-c3a8-4bd4-9d2b-9ca5600727a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91481de3-0433-4c60-a29d-74dfad4a1200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12391c2-d2ed-4fa8-8061-00ae3023d6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b02968-afc1-42c9-8e28-0e55f63f4284</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bb3a48e-a324-4625-b059-10119d784fb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Dashboard/03 - Leave/02 - Negative/TC_032_SickLeaveFail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f536f59-8429-4c27-ba03-e888e61ceead</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae911c0-c3a8-4bd4-9d2b-9ca5600727a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91481de3-0433-4c60-a29d-74dfad4a1200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12391c2-d2ed-4fa8-8061-00ae3023d6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b02968-afc1-42c9-8e28-0e55f63f4284</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
