<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_007_Delete Job Titles</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>55c31651-1eb0-47e4-9764-6100b9cd871c</testSuiteGuid>
   <testCaseLink>
      <guid>8587d06e-5d0c-4c45-a9e1-f945cbba6978</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Job Titles/02 - Delete Job Titles/01 _Positive/TC_022_DeleteAJobTitle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9e1bdd-909c-4cac-bcd1-ca7553891661</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>802b9ef6-71ae-4ae6-955d-e3d20cfdb74c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04 - Job Titles/02 - Delete Job Titles/01 _Positive/TC_023_DeleteMoreJobTitles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9e1bdd-909c-4cac-bcd1-ca7553891661</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6b68695-a062-4ae1-8dda-e1b0fcd7c5d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5dcfe00-9cc0-44fa-8a0d-751ac0e415fe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
