<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add</name>
   <tag></tag>
   <elementGuidId>214164bb-db9e-461d-9894-09e9e93f00a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_Add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ba429f8-f531-4f62-9feb-1270736dab73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_primary </value>
      <webElementGuid>7238d0ac-73f0-4986-9097-19a3eb377a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Add</value>
      <webElementGuid>26aa2fb1-3aa7-4fcd-afa3-65bd38036835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:addHobbiesRecord();return false;</value>
      <webElementGuid>ce97330d-5880-4b68-bfd5-56321d7ad72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>fb8dc400-2271-47ed-9ecd-cf215e7ce4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Add&quot;)</value>
      <webElementGuid>1cc396c5-e3bd-45fe-9fc7-2ab6c5a8549b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/01 - Profile/TC_042_AddProfileDetails/Page_Home page/Hobbies/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>dbc926ae-0191-4e37-a9ee-8a6cb97455f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Add']</value>
      <webElementGuid>6ec94f1e-52fd-4ff0-9559-dd53521019e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[11]/div/div[2]/ul/li/a</value>
      <webElementGuid>143253f4-edf3-4ab7-81f1-119cc1eeb6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add')])[2]</value>
      <webElementGuid>ef2407d3-af9b-463a-9bb5-cbba69b071c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Hobbies &amp; Interests'])[1]/following::a[1]</value>
      <webElementGuid>0dc0bea4-7429-4027-8681-d6baad5c041f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy policy'])[1]/following::a[1]</value>
      <webElementGuid>f1ed2b62-19c9-4a5c-a433-e81ebb4ee5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>73d7b769-4052-45af-a480-0fc35540fa57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record has been updated successfully.'])[1]/preceding::a[2]</value>
      <webElementGuid>accc30ba-4c13-41b6-9cf0-db03c4fadee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>48ee46c0-941a-42e7-8de0-f62a5d71c62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>359c4668-7d81-4f0a-ba6c-3a3acc1f453d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Add' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>4d019f55-586b-486d-b807-77840f695ca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
