<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Hobbies  Interests_hobbies0</name>
   <tag></tag>
   <elementGuidId>1f4e9ce9-fe4c-4310-9919-c9f0b369a306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hobbies0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hobbies0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @class = 'form-control' and @ref_element = 'Object Repository/TC05 - Self Services/01 - Profile/TC_042_AddProfileDetails/Page_Home page/Hobbies/Page_Home page/iframe_Self services_homePageFrame (1)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd567d9f-9b1a-498d-bb71-1d4adf5807be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a97d38f6-d718-4fc2-b97e-1052ec3ae441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>74f3c750-f4c5-48da-ba2b-b1a4bad9e0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies0</value>
      <webElementGuid>140c5632-9dac-4ee5-87d0-25bb1bea2ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>numericFilter(this);return false;</value>
      <webElementGuid>15095d06-c7fb-41f3-a03c-b6fc2716a0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobbies0&quot;)</value>
      <webElementGuid>ba1e0df6-d940-4ed0-9e0f-f79b9b9cb122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC05 - Self Services/01 - Profile/TC_042_AddProfileDetails/Page_Home page/Hobbies/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>8102af4b-d4f6-4132-aae9-bca61924b3ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hobbies0']</value>
      <webElementGuid>b06bf290-b788-4931-8968-f52e3a5b08c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>bdffd74e-261d-4163-9fe8-67fd9becd4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>85ca3c48-49cc-4a26-bb20-5db7081e8d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'hobbies0']</value>
      <webElementGuid>42b4bf5b-1252-4f26-a707-8fab4a2b80f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
