<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comment Section</name>
   <tag></tag>
   <elementGuidId>ccfb7e5d-3377-46e9-a6d7-1532b6bec390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_reponse_note_1000011</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[8]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>923c86cb-e2c7-4a99-ba63-bdfe74703345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9bd426b-7475-4d82-b617-0056203e17d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_reponse_note_1000011</value>
      <webElementGuid>3dd78ef2-ac8c-4d8c-9489-902db645022b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c85a3ce2-d53f-4449-973a-9bc5599a51d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your comment</value>
      <webElementGuid>09943514-feb5-4bfb-8464-1a40e54abd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_reponse_note_1000011&quot;)</value>
      <webElementGuid>eacf846e-4a6e-480a-bbc0-64abf0b1a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/02 - Feed/TC_017_AddComment/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>c48f69bf-f098-4b80-92fc-72656713994d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_reponse_note_1000011']</value>
      <webElementGuid>444210ae-1c4d-41d5-a75e-aa51ae908909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buddy_box_1000011']/div[8]/div/div/input</value>
      <webElementGuid>6d205f3b-bf3f-47ad-b423-943f702ba35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[8]/div/div/input</value>
      <webElementGuid>395b3e9d-48f5-48ba-b50e-5544191e5842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_reponse_note_1000011' and @placeholder = 'Enter your comment']</value>
      <webElementGuid>edbe8414-0f53-4ea0-9467-5f973bcdc503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
