<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Say hello to emp 10 on joining  as Default__reponse_note_1000012</name>
   <tag></tag>
   <elementGuidId>5706c76c-6d9a-495e-9744-dfd3606a6250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_reponse_note_1000012</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_reponse_note_1000012']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7af03f1a-4438-444f-a13e-86b5c38cac45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15b13e3f-e10c-4c3b-8a79-47a10802a1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_reponse_note_1000012</value>
      <webElementGuid>2fe01a65-3c28-4e7b-b7f2-28aacb55f6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f3100025-7ccc-4dc8-8a9d-da937193e0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your comment</value>
      <webElementGuid>f0e1e96d-dff5-40cf-9a67-c850d0d5f74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_reponse_note_1000012&quot;)</value>
      <webElementGuid>1e4f90ab-eabf-4f82-890b-5ed5a2dedb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC04 - Dashboard/02 - Feed/TC_017_AddComment/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>616d2a64-6a74-4f02-b050-1aa7ff4a7dcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_reponse_note_1000012']</value>
      <webElementGuid>2682ab98-b21d-49dc-890e-360a5ab73d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buddy_box_1000012']/div[8]/div/div/input</value>
      <webElementGuid>2d853b53-493f-4c10-bff6-0711780b8ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>c79a743c-939f-490c-8abf-516e29000b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_reponse_note_1000012' and @placeholder = 'Enter your comment']</value>
      <webElementGuid>5d2b4b8d-b451-4e7f-821b-6c03932c28b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
